//
// Maya/MEL export data written by 3DEqualizer4 Release 5
//
// All lengths are in centimeter, all angles are in degree.
//

// create scene group...
string $sceneGroupName = `group -em -name "Scene"`;

// create camera camera_1_1...
string $cameraNodes[] = `camera -name "camera_1_1" -hfa 1.417322834645669  -vfa 0.797244094488189 -fl 35.000000000000000 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation -72.318457734100207 85.121973501800369 -109.063495108999831 $cameraTransform;
xform -rotation -34.200000000000053 -40.799999999999983 0.000000000000010 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $myImagePlane[] = `imagePlane -camera $cameraTransform` ;
setAttr ($myImagePlane[1] + ".offsetX") -0.000000000000000;
setAttr ($myImagePlane[1] + ".offsetY") -0.000000000000000;
setAttr ($myImagePlane[1]+".useFrameExtension") 1;
expression -n "frame_ext_expression" -s ($myImagePlane[1]+".frameExtension=frame");
setAttr ($myImagePlane[1] + ".imageName") -type "string" "c:/Users/hko/Documents/mmlec/week4/plate/png/object_tracking.0001.png";
setAttr ($myImagePlane[1] + ".fit") 4;
setAttr ($myImagePlane[1] + ".displayOnlyIfCurrent") 1;
setAttr ($myImagePlane[1]  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;

// animating camera camera_1_1...
playbackOptions -min 1 -max 120;

setKeyframe -at translateX -t 1 -v -72.318457734100207 $cameraTransform; 
setKeyframe -at translateY -t 1 -v 85.121973501800369 $cameraTransform; 
setKeyframe -at translateZ -t 1 -v -109.063495108999831 $cameraTransform; 
setKeyframe -at rotateX -t 1 -v -34.200000000000053 $cameraTransform; 
setKeyframe -at rotateY -t 1 -v -40.799999999999983 $cameraTransform; 
setKeyframe -at rotateZ -t 1 -v 0.000000000000010 $cameraTransform; 
setKeyframe -at focalLength -t 1 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 2 -v -71.055588287500200 $cameraTransform; 
setKeyframe -at translateY -t 2 -v 85.006443846100396 $cameraTransform; 
setKeyframe -at translateZ -t 2 -v -104.965540336999823 $cameraTransform; 
setKeyframe -at rotateX -t 2 -v -34.164705882400085 $cameraTransform; 
setKeyframe -at rotateY -t 2 -v -40.070588235300043 $cameraTransform; 
setKeyframe -at rotateZ -t 2 -v 0.000000000000017 $cameraTransform; 
setKeyframe -at focalLength -t 2 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 3 -v -69.785208235800113 $cameraTransform; 
setKeyframe -at translateY -t 3 -v 84.891753433600300 $cameraTransform; 
setKeyframe -at translateZ -t 3 -v -100.866893706999804 $cameraTransform; 
setKeyframe -at rotateX -t 3 -v -34.129411764700052 $cameraTransform; 
setKeyframe -at rotateY -t 3 -v -39.341176470600011 $cameraTransform; 
setKeyframe -at rotateZ -t 3 -v 0.000000000000013 $cameraTransform; 
setKeyframe -at focalLength -t 3 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 4 -v -68.507248669000120 $cameraTransform; 
setKeyframe -at translateY -t 4 -v 84.778118216600234 $cameraTransform; 
setKeyframe -at translateZ -t 4 -v -96.767871245799853 $cameraTransform; 
setKeyframe -at rotateX -t 4 -v -34.094117647100028 $cameraTransform; 
setKeyframe -at rotateY -t 4 -v -38.611764705899994 $cameraTransform; 
setKeyframe -at rotateZ -t 4 -v -0.000000000000004 $cameraTransform; 
setKeyframe -at focalLength -t 4 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 5 -v -67.221640677200071 $cameraTransform; 
setKeyframe -at translateY -t 5 -v 84.665754147400307 $cameraTransform; 
setKeyframe -at translateZ -t 5 -v -92.668788982399803 $cameraTransform; 
setKeyframe -at rotateX -t 5 -v -34.058823529400065 $cameraTransform; 
setKeyframe -at rotateY -t 5 -v -37.882352941199983 $cameraTransform; 
setKeyframe -at rotateZ -t 5 -v -0.000000000000010 $cameraTransform; 
setKeyframe -at focalLength -t 5 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 6 -v -65.928315350200052 $cameraTransform; 
setKeyframe -at translateY -t 6 -v 84.554877178500263 $cameraTransform; 
setKeyframe -at translateZ -t 6 -v -88.569962945099832 $cameraTransform; 
setKeyframe -at rotateX -t 6 -v -34.023529411800048 $cameraTransform; 
setKeyframe -at rotateY -t 6 -v -37.152941176499986 $cameraTransform; 
setKeyframe -at rotateZ -t 6 -v -0.000000000000008 $cameraTransform; 
setKeyframe -at focalLength -t 6 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 7 -v -64.627203778200069 $cameraTransform; 
setKeyframe -at translateY -t 7 -v 84.445703262300242 $cameraTransform; 
setKeyframe -at translateZ -t 7 -v -84.471709162099870 $cameraTransform; 
setKeyframe -at rotateX -t 7 -v -33.988235294100051 $cameraTransform; 
setKeyframe -at rotateY -t 7 -v -36.423529411799962 $cameraTransform; 
setKeyframe -at rotateZ -t 7 -v -0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 7 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 8 -v -63.318237051100141 $cameraTransform; 
setKeyframe -at translateY -t 8 -v 84.338448351100240 $cameraTransform; 
setKeyframe -at translateZ -t 8 -v -80.374343661699896 $cameraTransform; 
setKeyframe -at rotateX -t 8 -v -33.952941176500062 $cameraTransform; 
setKeyframe -at rotateY -t 8 -v -35.694117647100022 $cameraTransform; 
setKeyframe -at rotateZ -t 8 -v 0.000000000000025 $cameraTransform; 
setKeyframe -at focalLength -t 8 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 9 -v -62.001346258900135 $cameraTransform; 
setKeyframe -at translateY -t 9 -v 84.233328397200410 $cameraTransform; 
setKeyframe -at translateZ -t 9 -v -76.278182472399834 $cameraTransform; 
setKeyframe -at rotateX -t 9 -v -33.917647058800100 $cameraTransform; 
setKeyframe -at rotateY -t 9 -v -34.964705882399990 $cameraTransform; 
setKeyframe -at rotateZ -t 9 -v 0.000000000000000 $cameraTransform; 
setKeyframe -at focalLength -t 9 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 10 -v -60.676462491700121 $cameraTransform; 
setKeyframe -at translateY -t 10 -v 84.130559353200283 $cameraTransform; 
setKeyframe -at translateZ -t 10 -v -72.183541622199897 $cameraTransform; 
setKeyframe -at rotateX -t 10 -v -33.882352941200054 $cameraTransform; 
setKeyframe -at rotateY -t 10 -v -34.235294117600013 $cameraTransform; 
setKeyframe -at rotateZ -t 10 -v 0.000000000000008 $cameraTransform; 
setKeyframe -at focalLength -t 10 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 11 -v -59.343516839400095 $cameraTransform; 
setKeyframe -at translateY -t 11 -v 84.030357171300267 $cameraTransform; 
setKeyframe -at translateZ -t 11 -v -68.090737139699883 $cameraTransform; 
setKeyframe -at rotateX -t 11 -v -33.847058823500070 $cameraTransform; 
setKeyframe -at rotateY -t 11 -v -33.505882352900009 $cameraTransform; 
setKeyframe -at rotateZ -t 11 -v 0.000000000000010 $cameraTransform; 
setKeyframe -at focalLength -t 11 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 12 -v -58.002440392000132 $cameraTransform; 
setKeyframe -at translateY -t 12 -v 83.932937804000275 $cameraTransform; 
setKeyframe -at translateZ -t 12 -v -64.000085053099838 $cameraTransform; 
setKeyframe -at rotateX -t 12 -v -33.811764705900046 $cameraTransform; 
setKeyframe -at rotateY -t 12 -v -32.776470588199984 $cameraTransform; 
setKeyframe -at rotateZ -t 12 -v -0.000000000000004 $cameraTransform; 
setKeyframe -at focalLength -t 12 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 13 -v -56.653164239500086 $cameraTransform; 
setKeyframe -at translateY -t 13 -v 83.838517203600148 $cameraTransform; 
setKeyframe -at translateZ -t 13 -v -59.911901390699910 $cameraTransform; 
setKeyframe -at rotateX -t 13 -v -33.776470588200020 $cameraTransform; 
setKeyframe -at rotateY -t 13 -v -32.047058823499988 $cameraTransform; 
setKeyframe -at rotateZ -t 13 -v -0.000000000000008 $cameraTransform; 
setKeyframe -at focalLength -t 13 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 14 -v -55.295619471900046 $cameraTransform; 
setKeyframe -at translateY -t 14 -v 83.747311322500238 $cameraTransform; 
setKeyframe -at translateZ -t 14 -v -55.826502180899894 $cameraTransform; 
setKeyframe -at rotateX -t 14 -v -33.741176470600038 $cameraTransform; 
setKeyframe -at rotateY -t 14 -v -31.317647058800013 $cameraTransform; 
setKeyframe -at rotateZ -t 14 -v 0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 14 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 15 -v -53.929737179300133 $cameraTransform; 
setKeyframe -at translateY -t 15 -v 83.659536113000399 $cameraTransform; 
setKeyframe -at translateZ -t 15 -v -51.744203451899807 $cameraTransform; 
setKeyframe -at rotateX -t 15 -v -33.705882352900076 $cameraTransform; 
setKeyframe -at rotateY -t 15 -v -30.588235294099981 $cameraTransform; 
setKeyframe -at rotateZ -t 15 -v -0.000000000000013 $cameraTransform; 
setKeyframe -at focalLength -t 15 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 16 -v -52.555448451600085 $cameraTransform; 
setKeyframe -at translateY -t 16 -v 83.575407527600348 $cameraTransform; 
setKeyframe -at translateZ -t 16 -v -47.665321232099842 $cameraTransform; 
setKeyframe -at rotateX -t 16 -v -33.670588235300045 $cameraTransform; 
setKeyframe -at rotateY -t 16 -v -29.858823529399999 $cameraTransform; 
setKeyframe -at rotateZ -t 16 -v -0.000000000000031 $cameraTransform; 
setKeyframe -at focalLength -t 16 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 17 -v -51.172684378900129 $cameraTransform; 
setKeyframe -at translateY -t 17 -v 83.495141518700422 $cameraTransform; 
setKeyframe -at translateZ -t 17 -v -43.590171549699789 $cameraTransform; 
setKeyframe -at rotateX -t 17 -v -33.635294117600068 $cameraTransform; 
setKeyframe -at rotateY -t 17 -v -29.129411764699991 $cameraTransform; 
setKeyframe -at rotateZ -t 17 -v -0.000000000000011 $cameraTransform; 
setKeyframe -at focalLength -t 17 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 18 -v -49.781376051100182 $cameraTransform; 
setKeyframe -at translateY -t 18 -v 83.418954038500416 $cameraTransform; 
setKeyframe -at translateZ -t 18 -v -39.519070433199801 $cameraTransform; 
setKeyframe -at rotateX -t 18 -v -33.600000000000051 $cameraTransform; 
setKeyframe -at rotateY -t 18 -v -28.399999999999984 $cameraTransform; 
setKeyframe -at rotateZ -t 18 -v -0.000000000000027 $cameraTransform; 
setKeyframe -at focalLength -t 18 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 19 -v -48.381454558200062 $cameraTransform; 
setKeyframe -at translateY -t 19 -v 83.347061039600305 $cameraTransform; 
setKeyframe -at translateZ -t 19 -v -35.452333910699821 $cameraTransform; 
setKeyframe -at rotateX -t 19 -v -33.564705882400048 $cameraTransform; 
setKeyframe -at rotateY -t 19 -v -27.670588235299991 $cameraTransform; 
setKeyframe -at rotateZ -t 19 -v -0.000000000000008 $cameraTransform; 
setKeyframe -at focalLength -t 19 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 20 -v -46.972850990300088 $cameraTransform; 
setKeyframe -at translateY -t 20 -v 83.279678474200352 $cameraTransform; 
setKeyframe -at translateZ -t 20 -v -31.390278010699774 $cameraTransform; 
setKeyframe -at rotateX -t 20 -v -33.529411764700065 $cameraTransform; 
setKeyframe -at rotateY -t 20 -v -26.941176470599974 $cameraTransform; 
setKeyframe -at rotateZ -t 20 -v -0.000000000000021 $cameraTransform; 
setKeyframe -at focalLength -t 20 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 21 -v -45.555496437400159 $cameraTransform; 
setKeyframe -at translateY -t 21 -v 83.217022294800387 $cameraTransform; 
setKeyframe -at translateZ -t 21 -v -27.333218761399792 $cameraTransform; 
setKeyframe -at rotateX -t 21 -v -33.494117647100083 $cameraTransform; 
setKeyframe -at rotateY -t 21 -v -26.211764705900027 $cameraTransform; 
setKeyframe -at rotateZ -t 21 -v 0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 21 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 22 -v -44.129321989300173 $cameraTransform; 
setKeyframe -at translateY -t 22 -v 83.159308453800392 $cameraTransform; 
setKeyframe -at translateZ -t 22 -v -23.281472191099795 $cameraTransform; 
setKeyframe -at rotateX -t 22 -v -33.458823529400050 $cameraTransform; 
setKeyframe -at rotateY -t 22 -v -25.482352941200034 $cameraTransform; 
setKeyframe -at rotateZ -t 22 -v 0.000000000000012 $cameraTransform; 
setKeyframe -at focalLength -t 22 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 23 -v -42.694258736200076 $cameraTransform; 
setKeyframe -at translateY -t 23 -v 83.106752903400377 $cameraTransform; 
setKeyframe -at translateZ -t 23 -v -19.235354328299820 $cameraTransform; 
setKeyframe -at rotateX -t 23 -v -33.423529411800082 $cameraTransform; 
setKeyframe -at rotateY -t 23 -v -24.752941176500002 $cameraTransform; 
setKeyframe -at rotateZ -t 23 -v 0.000000000000000 $cameraTransform; 
setKeyframe -at focalLength -t 23 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 24 -v -41.250237768100092 $cameraTransform; 
setKeyframe -at translateY -t 24 -v 83.059571596100199 $cameraTransform; 
setKeyframe -at translateZ -t 24 -v -15.195181201099871 $cameraTransform; 
setKeyframe -at rotateX -t 24 -v -33.388235294100070 $cameraTransform; 
setKeyframe -at rotateY -t 24 -v -24.023529411800023 $cameraTransform; 
setKeyframe -at rotateZ -t 24 -v 0.000000000000010 $cameraTransform; 
setKeyframe -at focalLength -t 24 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 25 -v -39.797190174900088 $cameraTransform; 
setKeyframe -at translateY -t 25 -v 83.017980484300409 $cameraTransform; 
setKeyframe -at translateZ -t 25 -v -11.161268837899797 $cameraTransform; 
setKeyframe -at rotateX -t 25 -v -33.352941176500082 $cameraTransform; 
setKeyframe -at rotateY -t 25 -v -23.294117647099998 $cameraTransform; 
setKeyframe -at rotateZ -t 25 -v -0.000000000000028 $cameraTransform; 
setKeyframe -at focalLength -t 25 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 26 -v -38.335047046700041 $cameraTransform; 
setKeyframe -at translateY -t 26 -v 82.982195520400182 $cameraTransform; 
setKeyframe -at translateZ -t 26 -v -7.133933266959957 $cameraTransform; 
setKeyframe -at rotateX -t 26 -v -33.317647058800034 $cameraTransform; 
setKeyframe -at rotateY -t 26 -v -22.564705882399995 $cameraTransform; 
setKeyframe -at rotateZ -t 26 -v -0.000000000000012 $cameraTransform; 
setKeyframe -at focalLength -t 26 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 27 -v -36.863739473500083 $cameraTransform; 
setKeyframe -at translateY -t 27 -v 82.952432656700324 $cameraTransform; 
setKeyframe -at translateZ -t 27 -v -3.113490516679803 $cameraTransform; 
setKeyframe -at rotateX -t 27 -v -33.282352941200052 $cameraTransform; 
setKeyframe -at rotateY -t 27 -v -21.835294117600014 $cameraTransform; 
setKeyframe -at rotateZ -t 27 -v 0.000000000000001 $cameraTransform; 
setKeyframe -at focalLength -t 27 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 28 -v -35.383198545100136 $cameraTransform; 
setKeyframe -at translateY -t 28 -v 82.928907845600406 $cameraTransform; 
setKeyframe -at translateZ -t 28 -v 0.899743384661207 $cameraTransform; 
setKeyframe -at rotateX -t 28 -v -33.247058823500069 $cameraTransform; 
setKeyframe -at rotateY -t 28 -v -21.105882352900011 $cameraTransform; 
setKeyframe -at rotateZ -t 28 -v 0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 28 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 29 -v -33.893355351800139 $cameraTransform; 
setKeyframe -at translateY -t 29 -v 82.911837039400297 $cameraTransform; 
setKeyframe -at translateZ -t 29 -v 4.905452408760141 $cameraTransform; 
setKeyframe -at rotateX -t 29 -v -33.211764705900066 $cameraTransform; 
setKeyframe -at rotateY -t 29 -v -20.376470588200036 $cameraTransform; 
setKeyframe -at rotateZ -t 29 -v 0.000000000000022 $cameraTransform; 
setKeyframe -at focalLength -t 29 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 30 -v -32.394140983400135 $cameraTransform; 
setKeyframe -at translateY -t 30 -v 82.901436190700338 $cameraTransform; 
setKeyframe -at translateZ -t 30 -v 8.903320527290134 $cameraTransform; 
setKeyframe -at rotateX -t 30 -v -33.176470588200068 $cameraTransform; 
setKeyframe -at rotateY -t 30 -v -19.647058823500032 $cameraTransform; 
setKeyframe -at rotateZ -t 30 -v 0.000000000000018 $cameraTransform; 
setKeyframe -at focalLength -t 30 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 31 -v -30.885486530000133 $cameraTransform; 
setKeyframe -at translateY -t 31 -v 82.897921251700311 $cameraTransform; 
setKeyframe -at translateZ -t 31 -v 12.893031711900193 $cameraTransform; 
setKeyframe -at rotateX -t 31 -v -33.141176470600051 $cameraTransform; 
setKeyframe -at rotateY -t 31 -v -18.917647058800029 $cameraTransform; 
setKeyframe -at rotateZ -t 31 -v 0.000000000000011 $cameraTransform; 
setKeyframe -at focalLength -t 31 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 32 -v -29.368984300299982 $cameraTransform; 
setKeyframe -at translateY -t 32 -v 82.902471870400248 $cameraTransform; 
setKeyframe -at translateZ -t 32 -v 16.877767270200167 $cameraTransform; 
setKeyframe -at rotateX -t 32 -v -33.105882352900011 $cameraTransform; 
setKeyframe -at rotateY -t 32 -v -18.188235294099957 $cameraTransform; 
setKeyframe -at rotateZ -t 32 -v -0.000000000000036 $cameraTransform; 
setKeyframe -at focalLength -t 32 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 33 -v -27.846322055200062 $cameraTransform; 
setKeyframe -at translateY -t 33 -v 82.916058520300297 $cameraTransform; 
setKeyframe -at translateZ -t 33 -v 20.860926634000180 $cameraTransform; 
setKeyframe -at rotateX -t 33 -v -33.070588235300043 $cameraTransform; 
setKeyframe -at rotateY -t 33 -v -17.458823529399996 $cameraTransform; 
setKeyframe -at rotateZ -t 33 -v 0.000000000000001 $cameraTransform; 
setKeyframe -at focalLength -t 33 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 34 -v -26.317573947200081 $cameraTransform; 
setKeyframe -at translateY -t 34 -v 82.938583391900224 $cameraTransform; 
setKeyframe -at translateZ -t 34 -v 24.842520871400126 $cameraTransform; 
setKeyframe -at rotateX -t 34 -v -33.035294117600046 $cameraTransform; 
setKeyframe -at rotateY -t 34 -v -16.729411764700025 $cameraTransform; 
setKeyframe -at rotateZ -t 34 -v 0.000000000000010 $cameraTransform; 
setKeyframe -at focalLength -t 34 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 35 -v -24.782814128500092 $cameraTransform; 
setKeyframe -at translateY -t 35 -v 82.969948675500291 $cameraTransform; 
setKeyframe -at translateZ -t 35 -v 28.822561050300180 $cameraTransform; 
setKeyframe -at rotateX -t 35 -v -33.000000000000028 $cameraTransform; 
setKeyframe -at rotateY -t 35 -v -16.000000000000014 $cameraTransform; 
setKeyframe -at rotateZ -t 35 -v 0.000000000000001 $cameraTransform; 
setKeyframe -at focalLength -t 35 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 36 -v -23.242116751500028 $cameraTransform; 
setKeyframe -at translateY -t 36 -v 83.010056561600237 $cameraTransform; 
setKeyframe -at translateZ -t 36 -v 32.801058238800124 $cameraTransform; 
setKeyframe -at rotateX -t 36 -v -32.964705882400004 $cameraTransform; 
setKeyframe -at rotateY -t 36 -v -15.270588235299975 $cameraTransform; 
setKeyframe -at rotateZ -t 36 -v -0.000000000000017 $cameraTransform; 
setKeyframe -at focalLength -t 36 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 37 -v -21.695555968400051 $cameraTransform; 
setKeyframe -at translateY -t 37 -v 83.058809240900374 $cameraTransform; 
setKeyframe -at translateZ -t 37 -v 36.778023504800188 $cameraTransform; 
setKeyframe -at rotateX -t 37 -v -32.929411764700056 $cameraTransform; 
setKeyframe -at rotateY -t 37 -v -14.541176470599998 $cameraTransform; 
setKeyframe -at rotateZ -t 37 -v -0.000000000000005 $cameraTransform; 
setKeyframe -at focalLength -t 37 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 38 -v -20.143205931600065 $cameraTransform; 
setKeyframe -at translateY -t 38 -v 83.116108903600292 $cameraTransform; 
setKeyframe -at translateZ -t 38 -v 40.753467916400183 $cameraTransform; 
setKeyframe -at rotateX -t 38 -v -32.894117647100060 $cameraTransform; 
setKeyframe -at rotateY -t 38 -v -13.811764705900011 $cameraTransform; 
setKeyframe -at rotateZ -t 38 -v 0.000000000000003 $cameraTransform; 
setKeyframe -at focalLength -t 38 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 39 -v -18.585140793400100 $cameraTransform; 
setKeyframe -at translateY -t 39 -v 83.181857740300316 $cameraTransform; 
setKeyframe -at translateZ -t 39 -v 44.727402541500226 $cameraTransform; 
setKeyframe -at rotateX -t 39 -v -32.858823529400084 $cameraTransform; 
setKeyframe -at rotateY -t 39 -v -13.082352941200021 $cameraTransform; 
setKeyframe -at rotateZ -t 39 -v 0.000000000000013 $cameraTransform; 
setKeyframe -at focalLength -t 39 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 40 -v -17.021434706100063 $cameraTransform; 
setKeyframe -at translateY -t 40 -v 83.255957941400297 $cameraTransform; 
setKeyframe -at translateZ -t 40 -v 48.699838448200182 $cameraTransform; 
setKeyframe -at rotateX -t 40 -v -32.823529411800052 $cameraTransform; 
setKeyframe -at rotateY -t 40 -v -12.352941176500007 $cameraTransform; 
setKeyframe -at rotateZ -t 40 -v 0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 40 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 41 -v -15.452161822000051 $cameraTransform; 
setKeyframe -at translateY -t 41 -v 83.338311697500245 $cameraTransform; 
setKeyframe -at translateZ -t 41 -v 52.670786704400143 $cameraTransform; 
setKeyframe -at rotateX -t 41 -v -32.788235294100041 $cameraTransform; 
setKeyframe -at rotateY -t 41 -v -11.623529411800002 $cameraTransform; 
setKeyframe -at rotateZ -t 41 -v 0.000000000000009 $cameraTransform; 
setKeyframe -at focalLength -t 41 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 42 -v -13.877396293400007 $cameraTransform; 
setKeyframe -at translateY -t 42 -v 83.428821199000282 $cameraTransform; 
setKeyframe -at translateZ -t 42 -v 56.640258378100185 $cameraTransform; 
setKeyframe -at rotateX -t 42 -v -32.752941176500087 $cameraTransform; 
setKeyframe -at rotateY -t 42 -v -10.894117647099996 $cameraTransform; 
setKeyframe -at rotateZ -t 42 -v -0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 42 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 43 -v -12.297212272700005 $cameraTransform; 
setKeyframe -at translateY -t 43 -v 83.527388636300287 $cameraTransform; 
setKeyframe -at translateZ -t 43 -v 60.608264537300187 $cameraTransform; 
setKeyframe -at rotateX -t 43 -v -32.717647058800047 $cameraTransform; 
setKeyframe -at rotateY -t 43 -v -10.164705882399998 $cameraTransform; 
setKeyframe -at rotateZ -t 43 -v -0.000000000000008 $cameraTransform; 
setKeyframe -at focalLength -t 43 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 44 -v -10.711683912199970 $cameraTransform; 
setKeyframe -at translateY -t 44 -v 83.633916200000272 $cameraTransform; 
setKeyframe -at translateZ -t 44 -v 64.574816250100213 $cameraTransform; 
setKeyframe -at rotateX -t 44 -v -32.682352941200030 $cameraTransform; 
setKeyframe -at rotateY -t 44 -v -9.435294117649981 $cameraTransform; 
setKeyframe -at rotateZ -t 44 -v -0.000000000000020 $cameraTransform; 
setKeyframe -at focalLength -t 44 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 45 -v -9.120885364120092 $cameraTransform; 
setKeyframe -at translateY -t 45 -v 83.748306080500413 $cameraTransform; 
setKeyframe -at translateZ -t 45 -v 68.539924584500298 $cameraTransform; 
setKeyframe -at rotateX -t 45 -v -32.647058823500039 $cameraTransform; 
setKeyframe -at rotateY -t 45 -v -8.705882352940012 $cameraTransform; 
setKeyframe -at rotateZ -t 45 -v 0.000000000000009 $cameraTransform; 
setKeyframe -at focalLength -t 45 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 46 -v -7.524890780870042 $cameraTransform; 
setKeyframe -at translateY -t 46 -v 83.870460468300294 $cameraTransform; 
setKeyframe -at translateZ -t 46 -v 72.503600608300204 $cameraTransform; 
setKeyframe -at rotateX -t 46 -v -32.611764705900050 $cameraTransform; 
setKeyframe -at rotateY -t 46 -v -7.976470588240004 $cameraTransform; 
setKeyframe -at rotateZ -t 46 -v 0.000000000000000 $cameraTransform; 
setKeyframe -at focalLength -t 46 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 47 -v -5.923774314740033 $cameraTransform; 
setKeyframe -at translateY -t 47 -v 84.000281553800306 $cameraTransform; 
setKeyframe -at translateZ -t 47 -v 76.465855389700224 $cameraTransform; 
setKeyframe -at rotateX -t 47 -v -32.576470588200053 $cameraTransform; 
setKeyframe -at rotateY -t 47 -v -7.247058823530001 $cameraTransform; 
setKeyframe -at rotateZ -t 47 -v -0.000000000000003 $cameraTransform; 
setKeyframe -at focalLength -t 47 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 48 -v -4.317610118040051 $cameraTransform; 
setKeyframe -at translateY -t 48 -v 84.137671527600318 $cameraTransform; 
setKeyframe -at translateZ -t 48 -v 80.426699996600192 $cameraTransform; 
setKeyframe -at rotateX -t 48 -v -32.541176470600028 $cameraTransform; 
setKeyframe -at rotateY -t 48 -v -6.517647058819997 $cameraTransform; 
setKeyframe -at rotateZ -t 48 -v 0.000000000000001 $cameraTransform; 
setKeyframe -at focalLength -t 48 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 49 -v -2.706472343090038 $cameraTransform; 
setKeyframe -at translateY -t 49 -v 84.282532580000392 $cameraTransform; 
setKeyframe -at translateZ -t 49 -v 84.386145497000271 $cameraTransform; 
setKeyframe -at rotateX -t 49 -v -32.505882352900095 $cameraTransform; 
setKeyframe -at rotateY -t 49 -v -5.788235294120008 $cameraTransform; 
setKeyframe -at rotateZ -t 49 -v 0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 49 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 50 -v -1.090435142190007 $cameraTransform; 
setKeyframe -at translateY -t 50 -v 84.434766901700215 $cameraTransform; 
setKeyframe -at translateZ -t 50 -v 88.344202959000143 $cameraTransform; 
setKeyframe -at rotateX -t 50 -v -32.470588235300021 $cameraTransform; 
setKeyframe -at rotateY -t 50 -v -5.058823529409995 $cameraTransform; 
setKeyframe -at rotateZ -t 50 -v -0.000000000000004 $cameraTransform; 
setKeyframe -at focalLength -t 50 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 51 -v 0.530427332317968 $cameraTransform; 
setKeyframe -at translateY -t 51 -v 84.594276682900272 $cameraTransform; 
setKeyframe -at translateZ -t 51 -v 92.300883450400192 $cameraTransform; 
setKeyframe -at rotateX -t 51 -v -32.435294117600087 $cameraTransform; 
setKeyframe -at rotateY -t 51 -v -4.329411764710009 $cameraTransform; 
setKeyframe -at rotateZ -t 51 -v 0.000000000000004 $cameraTransform; 
setKeyframe -at focalLength -t 51 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 52 -v 2.156040928140014 $cameraTransform; 
setKeyframe -at translateY -t 52 -v 84.760964114300364 $cameraTransform; 
setKeyframe -at translateZ -t 52 -v 96.256198039400303 $cameraTransform; 
setKeyframe -at rotateX -t 52 -v -32.400000000000041 $cameraTransform; 
setKeyframe -at rotateY -t 52 -v -3.599999999999989 $cameraTransform; 
setKeyframe -at rotateZ -t 52 -v -0.000000000000012 $cameraTransform; 
setKeyframe -at focalLength -t 52 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 53 -v 3.786331492939959 $cameraTransform; 
setKeyframe -at translateY -t 53 -v 84.934731386300385 $cameraTransform; 
setKeyframe -at translateZ -t 53 -v 100.210157794000267 $cameraTransform; 
setKeyframe -at rotateX -t 53 -v -32.364705882400060 $cameraTransform; 
setKeyframe -at rotateY -t 53 -v -2.870588235290013 $cameraTransform; 
setKeyframe -at rotateZ -t 53 -v 0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 53 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 54 -v 5.421224874419986 $cameraTransform; 
setKeyframe -at translateY -t 54 -v 85.115480689300313 $cameraTransform; 
setKeyframe -at translateZ -t 54 -v 104.162773782000286 $cameraTransform; 
setKeyframe -at rotateX -t 54 -v -32.329411764700019 $cameraTransform; 
setKeyframe -at rotateY -t 54 -v -2.141176470589999 $cameraTransform; 
setKeyframe -at rotateZ -t 54 -v -0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 54 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 55 -v 7.060646920259989 $cameraTransform; 
setKeyframe -at translateY -t 55 -v 85.303114213900230 $cameraTransform; 
setKeyframe -at translateZ -t 55 -v 108.114057071000104 $cameraTransform; 
setKeyframe -at rotateX -t 55 -v -32.294117647100080 $cameraTransform; 
setKeyframe -at rotateY -t 55 -v -1.411764705880003 $cameraTransform; 
setKeyframe -at rotateZ -t 55 -v -0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 55 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 56 -v 8.704523478140008 $cameraTransform; 
setKeyframe -at translateY -t 56 -v 85.497534150500059 $cameraTransform; 
setKeyframe -at translateZ -t 56 -v 112.064018730000029 $cameraTransform; 
setKeyframe -at rotateX -t 56 -v -32.258823529399997 $cameraTransform; 
setKeyframe -at rotateY -t 56 -v -0.682352941176994 $cameraTransform; 
setKeyframe -at rotateZ -t 56 -v -0.000000000000010 $cameraTransform; 
setKeyframe -at focalLength -t 56 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 57 -v 10.352780395800012 $cameraTransform; 
setKeyframe -at translateY -t 57 -v 85.698642689500304 $cameraTransform; 
setKeyframe -at translateZ -t 57 -v 116.012669827000195 $cameraTransform; 
setKeyframe -at rotateX -t 57 -v -32.223529411800058 $cameraTransform; 
setKeyframe -at rotateY -t 57 -v 0.047058823529303 $cameraTransform; 
setKeyframe -at rotateZ -t 57 -v 0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 57 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 58 -v 12.005343520799990 $cameraTransform; 
setKeyframe -at translateY -t 58 -v 85.906342021500336 $cameraTransform; 
setKeyframe -at translateZ -t 58 -v 119.960021429000207 $cameraTransform; 
setKeyframe -at rotateX -t 58 -v -32.188235294100039 $cameraTransform; 
setKeyframe -at rotateY -t 58 -v 0.776470588234997 $cameraTransform; 
setKeyframe -at rotateZ -t 58 -v 0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 58 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 59 -v 13.662138700899945 $cameraTransform; 
setKeyframe -at translateY -t 59 -v 86.120534337000350 $cameraTransform; 
setKeyframe -at translateZ -t 59 -v 123.906084604000270 $cameraTransform; 
setKeyframe -at rotateX -t 59 -v -32.152941176500072 $cameraTransform; 
setKeyframe -at rotateY -t 59 -v 1.505882352939981 $cameraTransform; 
setKeyframe -at rotateZ -t 59 -v 0.000000000000011 $cameraTransform; 
setKeyframe -at focalLength -t 59 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 60 -v 15.323091783800010 $cameraTransform; 
setKeyframe -at translateY -t 60 -v 86.341121826300338 $cameraTransform; 
setKeyframe -at translateZ -t 60 -v 127.850870421000280 $cameraTransform; 
setKeyframe -at rotateX -t 60 -v -32.117647058800031 $cameraTransform; 
setKeyframe -at rotateY -t 60 -v 2.235294117649997 $cameraTransform; 
setKeyframe -at rotateZ -t 60 -v 0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 60 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 61 -v 16.988128617100031 $cameraTransform; 
setKeyframe -at translateY -t 61 -v 86.568006679900336 $cameraTransform; 
setKeyframe -at translateZ -t 61 -v 131.794389948000259 $cameraTransform; 
setKeyframe -at rotateX -t 61 -v -32.082352941200043 $cameraTransform; 
setKeyframe -at rotateY -t 61 -v 2.964705882350005 $cameraTransform; 
setKeyframe -at rotateZ -t 61 -v -0.000000000000005 $cameraTransform; 
setKeyframe -at focalLength -t 61 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 62 -v 18.657175048599989 $cameraTransform; 
setKeyframe -at translateY -t 62 -v 86.801091088400256 $cameraTransform; 
setKeyframe -at translateZ -t 62 -v 135.736654252000193 $cameraTransform; 
setKeyframe -at rotateX -t 62 -v -32.047058823500052 $cameraTransform; 
setKeyframe -at rotateY -t 62 -v 3.694117647059993 $cameraTransform; 
setKeyframe -at rotateZ -t 62 -v 0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 62 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 63 -v 20.330156926000054 $cameraTransform; 
setKeyframe -at translateY -t 63 -v 87.040277242300391 $cameraTransform; 
setKeyframe -at translateZ -t 63 -v 139.677674401000303 $cameraTransform; 
setKeyframe -at rotateX -t 63 -v -32.011764705900084 $cameraTransform; 
setKeyframe -at rotateY -t 63 -v 4.423529411760010 $cameraTransform; 
setKeyframe -at rotateZ -t 63 -v -0.000000000000005 $cameraTransform; 
setKeyframe -at focalLength -t 63 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 64 -v 22.007000096800038 $cameraTransform; 
setKeyframe -at translateY -t 64 -v 87.285467331900207 $cameraTransform; 
setKeyframe -at translateZ -t 64 -v 143.617461464000115 $cameraTransform; 
setKeyframe -at rotateX -t 64 -v -31.976470588200073 $cameraTransform; 
setKeyframe -at rotateY -t 64 -v 5.152941176470009 $cameraTransform; 
setKeyframe -at rotateZ -t 64 -v -0.000000000000001 $cameraTransform; 
setKeyframe -at focalLength -t 64 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 65 -v 23.687630408900009 $cameraTransform; 
setKeyframe -at translateY -t 65 -v 87.536563547700396 $cameraTransform; 
setKeyframe -at translateZ -t 65 -v 147.556026509000219 $cameraTransform; 
setKeyframe -at rotateX -t 65 -v -31.941176470600041 $cameraTransform; 
setKeyframe -at rotateY -t 65 -v 5.882352941179990 $cameraTransform; 
setKeyframe -at rotateZ -t 65 -v 0.000000000000004 $cameraTransform; 
setKeyframe -at focalLength -t 65 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 66 -v 25.371973709800017 $cameraTransform; 
setKeyframe -at translateY -t 66 -v 87.793468080300372 $cameraTransform; 
setKeyframe -at translateZ -t 66 -v 151.493380603000247 $cameraTransform; 
setKeyframe -at rotateX -t 66 -v -31.905882352900054 $cameraTransform; 
setKeyframe -at rotateY -t 66 -v 6.611764705879995 $cameraTransform; 
setKeyframe -at rotateZ -t 66 -v 0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 66 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 67 -v 27.059955847300014 $cameraTransform; 
setKeyframe -at translateY -t 67 -v 88.056083120000380 $cameraTransform; 
setKeyframe -at translateZ -t 67 -v 155.429534814000277 $cameraTransform; 
setKeyframe -at rotateX -t 67 -v -31.870588235300044 $cameraTransform; 
setKeyframe -at rotateY -t 67 -v 7.341176470589991 $cameraTransform; 
setKeyframe -at rotateZ -t 67 -v -0.000000000000001 $cameraTransform; 
setKeyframe -at focalLength -t 67 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 68 -v 28.751502669100013 $cameraTransform; 
setKeyframe -at translateY -t 68 -v 88.324310857500322 $cameraTransform; 
setKeyframe -at translateZ -t 68 -v 159.364500211000262 $cameraTransform; 
setKeyframe -at rotateX -t 68 -v -31.835294117600071 $cameraTransform; 
setKeyframe -at rotateY -t 68 -v 8.070588235289994 $cameraTransform; 
setKeyframe -at rotateZ -t 68 -v 0.000000000000010 $cameraTransform; 
setKeyframe -at focalLength -t 68 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 69 -v 30.446540022799994 $cameraTransform; 
setKeyframe -at translateY -t 69 -v 88.598053483000385 $cameraTransform; 
setKeyframe -at translateZ -t 69 -v 163.298287861000290 $cameraTransform; 
setKeyframe -at rotateX -t 69 -v -31.800000000000068 $cameraTransform; 
setKeyframe -at rotateY -t 69 -v 8.799999999999994 $cameraTransform; 
setKeyframe -at rotateZ -t 69 -v 0.000000000000008 $cameraTransform; 
setKeyframe -at focalLength -t 69 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 70 -v 32.144993756100099 $cameraTransform; 
setKeyframe -at translateY -t 70 -v 88.877213187200297 $cameraTransform; 
setKeyframe -at translateZ -t 70 -v 167.230908833000228 $cameraTransform; 
setKeyframe -at rotateX -t 70 -v -31.764705882400023 $cameraTransform; 
setKeyframe -at rotateY -t 70 -v 9.529411764710014 $cameraTransform; 
setKeyframe -at rotateZ -t 70 -v -0.000000000000009 $cameraTransform; 
setKeyframe -at focalLength -t 70 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 71 -v 33.846789716700080 $cameraTransform; 
setKeyframe -at translateY -t 71 -v 89.161692160500323 $cameraTransform; 
setKeyframe -at translateZ -t 71 -v 171.162374194000222 $cameraTransform; 
setKeyframe -at rotateX -t 71 -v -31.729411764700050 $cameraTransform; 
setKeyframe -at rotateY -t 71 -v 10.258823529400017 $cameraTransform; 
setKeyframe -at rotateZ -t 71 -v 0.000000000000003 $cameraTransform; 
setKeyframe -at focalLength -t 71 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 72 -v 35.551853752300090 $cameraTransform; 
setKeyframe -at translateY -t 72 -v 89.451392593300355 $cameraTransform; 
setKeyframe -at translateZ -t 72 -v 175.092695013000224 $cameraTransform; 
setKeyframe -at rotateX -t 72 -v -31.694117647100047 $cameraTransform; 
setKeyframe -at rotateY -t 72 -v 10.988235294100013 $cameraTransform; 
setKeyframe -at rotateZ -t 72 -v -0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 72 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 73 -v 37.260111710600086 $cameraTransform; 
setKeyframe -at translateY -t 73 -v 89.746216676100389 $cameraTransform; 
setKeyframe -at translateZ -t 73 -v 179.021882357000294 $cameraTransform; 
setKeyframe -at rotateX -t 73 -v -31.658823529400070 $cameraTransform; 
setKeyframe -at rotateY -t 73 -v 11.717647058800011 $cameraTransform; 
setKeyframe -at rotateZ -t 73 -v -0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 73 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 74 -v 38.971489439300015 $cameraTransform; 
setKeyframe -at translateY -t 74 -v 90.046066599500236 $cameraTransform; 
setKeyframe -at translateZ -t 74 -v 182.949947295000158 $cameraTransform; 
setKeyframe -at rotateX -t 74 -v -31.623529411800057 $cameraTransform; 
setKeyframe -at rotateY -t 74 -v 12.447058823500001 $cameraTransform; 
setKeyframe -at rotateZ -t 74 -v 0.000000000000008 $cameraTransform; 
setKeyframe -at focalLength -t 74 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 75 -v 40.685912786000003 $cameraTransform; 
setKeyframe -at translateY -t 75 -v 90.350844553800215 $cameraTransform; 
setKeyframe -at translateZ -t 75 -v 186.876900894000130 $cameraTransform; 
setKeyframe -at rotateX -t 75 -v -31.588235294100027 $cameraTransform; 
setKeyframe -at rotateY -t 75 -v 13.176470588199978 $cameraTransform; 
setKeyframe -at rotateZ -t 75 -v 0.000000000000014 $cameraTransform; 
setKeyframe -at focalLength -t 75 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 76 -v 42.403307598400019 $cameraTransform; 
setKeyframe -at translateY -t 76 -v 90.660452729600451 $cameraTransform; 
setKeyframe -at translateZ -t 76 -v 190.802754223000335 $cameraTransform; 
setKeyframe -at rotateX -t 76 -v -31.552941176500052 $cameraTransform; 
setKeyframe -at rotateY -t 76 -v 13.905882352899978 $cameraTransform; 
setKeyframe -at rotateZ -t 76 -v 0.000000000000009 $cameraTransform; 
setKeyframe -at focalLength -t 76 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 77 -v 44.123599724200076 $cameraTransform; 
setKeyframe -at translateY -t 77 -v 90.974793317200323 $cameraTransform; 
setKeyframe -at translateZ -t 77 -v 194.727518349000263 $cameraTransform; 
setKeyframe -at rotateX -t 77 -v -31.517647058800044 $cameraTransform; 
setKeyframe -at rotateY -t 77 -v 14.635294117599997 $cameraTransform; 
setKeyframe -at rotateZ -t 77 -v 0.000000000000003 $cameraTransform; 
setKeyframe -at focalLength -t 77 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 78 -v 45.846715011200054 $cameraTransform; 
setKeyframe -at translateY -t 78 -v 91.293768507300328 $cameraTransform; 
setKeyframe -at translateZ -t 78 -v 198.651204340000277 $cameraTransform; 
setKeyframe -at rotateX -t 78 -v -31.482352941200041 $cameraTransform; 
setKeyframe -at rotateY -t 78 -v 15.364705882399987 $cameraTransform; 
setKeyframe -at rotateZ -t 78 -v 0.000000000000013 $cameraTransform; 
setKeyframe -at focalLength -t 78 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 79 -v 47.572579306900153 $cameraTransform; 
setKeyframe -at translateY -t 79 -v 91.617280490200429 $cameraTransform; 
setKeyframe -at translateZ -t 79 -v 202.573823265000271 $cameraTransform; 
setKeyframe -at rotateX -t 79 -v -31.447058823500061 $cameraTransform; 
setKeyframe -at rotateY -t 79 -v 16.094117647100020 $cameraTransform; 
setKeyframe -at rotateZ -t 79 -v -0.000000000000013 $cameraTransform; 
setKeyframe -at focalLength -t 79 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 80 -v 49.301118459000079 $cameraTransform; 
setKeyframe -at translateY -t 80 -v 91.945231456500323 $cameraTransform; 
setKeyframe -at translateZ -t 80 -v 206.495386192000268 $cameraTransform; 
setKeyframe -at rotateX -t 80 -v -31.411764705900048 $cameraTransform; 
setKeyframe -at rotateY -t 80 -v 16.823529411799999 $cameraTransform; 
setKeyframe -at rotateZ -t 80 -v 0.000000000000005 $cameraTransform; 
setKeyframe -at focalLength -t 80 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 81 -v 51.032258315400071 $cameraTransform; 
setKeyframe -at translateY -t 81 -v 92.277523596500373 $cameraTransform; 
setKeyframe -at translateZ -t 81 -v 210.415904187000251 $cameraTransform; 
setKeyframe -at rotateX -t 81 -v -31.376470588200036 $cameraTransform; 
setKeyframe -at rotateY -t 81 -v 17.552941176500003 $cameraTransform; 
setKeyframe -at rotateZ -t 81 -v 0.000000000000013 $cameraTransform; 
setKeyframe -at focalLength -t 81 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 82 -v 52.765924723500163 $cameraTransform; 
setKeyframe -at translateY -t 82 -v 92.614059100800517 $cameraTransform; 
setKeyframe -at translateZ -t 82 -v 214.335388321000352 $cameraTransform; 
setKeyframe -at rotateX -t 82 -v -31.341176470600082 $cameraTransform; 
setKeyframe -at rotateY -t 82 -v 18.282352941200028 $cameraTransform; 
setKeyframe -at rotateZ -t 82 -v -0.000000000000005 $cameraTransform; 
setKeyframe -at focalLength -t 82 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 83 -v 54.502043531200101 $cameraTransform; 
setKeyframe -at translateY -t 83 -v 92.954740159900297 $cameraTransform; 
setKeyframe -at translateZ -t 83 -v 218.253849659000196 $cameraTransform; 
setKeyframe -at rotateX -t 83 -v -31.305882352900028 $cameraTransform; 
setKeyframe -at rotateY -t 83 -v 19.011764705899996 $cameraTransform; 
setKeyframe -at rotateZ -t 83 -v 0.000000000000015 $cameraTransform; 
setKeyframe -at focalLength -t 83 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 84 -v 56.240540586100053 $cameraTransform; 
setKeyframe -at translateY -t 84 -v 93.299468964200301 $cameraTransform; 
setKeyframe -at translateZ -t 84 -v 222.171299272000169 $cameraTransform; 
setKeyframe -at rotateX -t 84 -v -31.270588235300096 $cameraTransform; 
setKeyframe -at rotateY -t 84 -v 19.741176470600013 $cameraTransform; 
setKeyframe -at rotateZ -t 84 -v 0.000000000000003 $cameraTransform; 
setKeyframe -at focalLength -t 84 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 85 -v 57.981341735800086 $cameraTransform; 
setKeyframe -at translateY -t 85 -v 93.648147704200269 $cameraTransform; 
setKeyframe -at translateZ -t 85 -v 226.087748225000240 $cameraTransform; 
setKeyframe -at rotateX -t 85 -v -31.235294117600009 $cameraTransform; 
setKeyframe -at rotateY -t 85 -v 20.470588235299978 $cameraTransform; 
setKeyframe -at rotateZ -t 85 -v 0.000000000000015 $cameraTransform; 
setKeyframe -at focalLength -t 85 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 86 -v 59.724372828100130 $cameraTransform; 
setKeyframe -at translateY -t 86 -v 94.000678570300394 $cameraTransform; 
setKeyframe -at translateZ -t 86 -v 230.003207588000237 $cameraTransform; 
setKeyframe -at rotateX -t 86 -v -31.200000000000038 $cameraTransform; 
setKeyframe -at rotateY -t 86 -v 21.200000000000006 $cameraTransform; 
setKeyframe -at rotateZ -t 86 -v 0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 86 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 87 -v 61.469559710700125 $cameraTransform; 
setKeyframe -at translateY -t 87 -v 94.356963753100402 $cameraTransform; 
setKeyframe -at translateZ -t 87 -v 233.917688429000293 $cameraTransform; 
setKeyframe -at rotateX -t 87 -v -31.164705882400042 $cameraTransform; 
setKeyframe -at rotateY -t 87 -v 21.929411764699999 $cameraTransform; 
setKeyframe -at rotateZ -t 87 -v 0.000000000000015 $cameraTransform; 
setKeyframe -at focalLength -t 87 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 88 -v 63.216828231300134 $cameraTransform; 
setKeyframe -at translateY -t 88 -v 94.716905443000428 $cameraTransform; 
setKeyframe -at translateZ -t 88 -v 237.831201815000270 $cameraTransform; 
setKeyframe -at rotateX -t 88 -v -31.129411764700055 $cameraTransform; 
setKeyframe -at rotateY -t 88 -v 22.658823529400010 $cameraTransform; 
setKeyframe -at rotateZ -t 88 -v 0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 88 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 89 -v 64.966104237400060 $cameraTransform; 
setKeyframe -at translateY -t 89 -v 95.080405830400295 $cameraTransform; 
setKeyframe -at translateZ -t 89 -v 241.743758814000159 $cameraTransform; 
setKeyframe -at rotateX -t 89 -v -31.094117647100070 $cameraTransform; 
setKeyframe -at rotateY -t 89 -v 23.388235294100010 $cameraTransform; 
setKeyframe -at rotateZ -t 89 -v 0.000000000000013 $cameraTransform; 
setKeyframe -at focalLength -t 89 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 90 -v 66.717313576800137 $cameraTransform; 
setKeyframe -at translateY -t 90 -v 95.447367106000328 $cameraTransform; 
setKeyframe -at translateZ -t 90 -v 245.655370495000255 $cameraTransform; 
setKeyframe -at rotateX -t 90 -v -31.058823529400019 $cameraTransform; 
setKeyframe -at rotateY -t 90 -v 24.117647058799989 $cameraTransform; 
setKeyframe -at rotateZ -t 90 -v 0.000000000000019 $cameraTransform; 
setKeyframe -at focalLength -t 90 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 91 -v 68.470382097300174 $cameraTransform; 
setKeyframe -at translateY -t 91 -v 95.817691460000390 $cameraTransform; 
setKeyframe -at translateZ -t 91 -v 249.566047925000248 $cameraTransform; 
setKeyframe -at rotateX -t 91 -v -31.023529411800052 $cameraTransform; 
setKeyframe -at rotateY -t 91 -v 24.847058823500021 $cameraTransform; 
setKeyframe -at rotateZ -t 91 -v 0.000000000000004 $cameraTransform; 
setKeyframe -at focalLength -t 91 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 92 -v 70.225235646400137 $cameraTransform; 
setKeyframe -at translateY -t 92 -v 96.191281083000362 $cameraTransform; 
setKeyframe -at translateZ -t 92 -v 253.475802173000204 $cameraTransform; 
setKeyframe -at rotateX -t 92 -v -30.988235294100033 $cameraTransform; 
setKeyframe -at rotateY -t 92 -v 25.576470588199989 $cameraTransform; 
setKeyframe -at rotateZ -t 92 -v 0.000000000000005 $cameraTransform; 
setKeyframe -at focalLength -t 92 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 93 -v 71.981800071900153 $cameraTransform; 
setKeyframe -at translateY -t 93 -v 96.568038165500354 $cameraTransform; 
setKeyframe -at translateZ -t 93 -v 257.384644306000212 $cameraTransform; 
setKeyframe -at rotateX -t 93 -v -30.952941176500062 $cameraTransform; 
setKeyframe -at rotateY -t 93 -v 26.305882352899985 $cameraTransform; 
setKeyframe -at rotateZ -t 93 -v 0.000000000000008 $cameraTransform; 
setKeyframe -at focalLength -t 93 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 94 -v 73.740001221400163 $cameraTransform; 
setKeyframe -at translateY -t 94 -v 96.947864897900445 $cameraTransform; 
setKeyframe -at translateZ -t 94 -v 261.292585392000319 $cameraTransform; 
setKeyframe -at rotateX -t 94 -v -30.917647058800050 $cameraTransform; 
setKeyframe -at rotateY -t 94 -v 27.035294117599999 $cameraTransform; 
setKeyframe -at rotateZ -t 94 -v 0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 94 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 95 -v 75.499764942700097 $cameraTransform; 
setKeyframe -at translateY -t 95 -v 97.330663470800317 $cameraTransform; 
setKeyframe -at translateZ -t 95 -v 265.199636500000167 $cameraTransform; 
setKeyframe -at rotateX -t 95 -v -30.882352941200022 $cameraTransform; 
setKeyframe -at rotateY -t 95 -v 27.764705882399973 $cameraTransform; 
setKeyframe -at rotateZ -t 95 -v 0.000000000000022 $cameraTransform; 
setKeyframe -at focalLength -t 95 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 96 -v 77.261017083300175 $cameraTransform; 
setKeyframe -at translateY -t 96 -v 97.716336074500390 $cameraTransform; 
setKeyframe -at translateZ -t 96 -v 269.105808697000271 $cameraTransform; 
setKeyframe -at rotateX -t 96 -v -30.847058823500056 $cameraTransform; 
setKeyframe -at rotateY -t 96 -v 28.494117647100019 $cameraTransform; 
setKeyframe -at rotateZ -t 96 -v 0.000000000000003 $cameraTransform; 
setKeyframe -at focalLength -t 96 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 97 -v 79.023683491100201 $cameraTransform; 
setKeyframe -at translateY -t 97 -v 98.104784899600389 $cameraTransform; 
setKeyframe -at translateZ -t 97 -v 273.011113052000212 $cameraTransform; 
setKeyframe -at rotateX -t 97 -v -30.811764705900057 $cameraTransform; 
setKeyframe -at rotateY -t 97 -v 29.223529411800012 $cameraTransform; 
setKeyframe -at rotateZ -t 97 -v -0.000000000000004 $cameraTransform; 
setKeyframe -at focalLength -t 97 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 98 -v 80.787690013600127 $cameraTransform; 
setKeyframe -at translateY -t 98 -v 98.495912136500323 $cameraTransform; 
setKeyframe -at translateZ -t 98 -v 276.915560632000222 $cameraTransform; 
setKeyframe -at rotateX -t 98 -v -30.776470588200038 $cameraTransform; 
setKeyframe -at rotateY -t 98 -v 29.952941176500012 $cameraTransform; 
setKeyframe -at rotateZ -t 98 -v 0.000000000000011 $cameraTransform; 
setKeyframe -at focalLength -t 98 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 99 -v 82.552962498600124 $cameraTransform; 
setKeyframe -at translateY -t 99 -v 98.889619975700299 $cameraTransform; 
setKeyframe -at translateZ -t 99 -v 280.819162506000168 $cameraTransform; 
setKeyframe -at rotateX -t 99 -v -30.741176470600035 $cameraTransform; 
setKeyframe -at rotateY -t 99 -v 30.682352941199987 $cameraTransform; 
setKeyframe -at rotateZ -t 99 -v 0.000000000000017 $cameraTransform; 
setKeyframe -at focalLength -t 99 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 100 -v 84.319426793800176 $cameraTransform; 
setKeyframe -at translateY -t 100 -v 99.285810607700327 $cameraTransform; 
setKeyframe -at translateZ -t 100 -v 284.721929740000235 $cameraTransform; 
setKeyframe -at rotateX -t 100 -v -30.705882352900034 $cameraTransform; 
setKeyframe -at rotateY -t 100 -v 31.411764705900030 $cameraTransform; 
setKeyframe -at rotateZ -t 100 -v -0.000000000000011 $cameraTransform; 
setKeyframe -at focalLength -t 100 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 101 -v 86.087008746800166 $cameraTransform; 
setKeyframe -at translateY -t 101 -v 99.684386222900400 $cameraTransform; 
setKeyframe -at translateZ -t 101 -v 288.623873405000268 $cameraTransform; 
setKeyframe -at rotateX -t 101 -v -30.670588235300070 $cameraTransform; 
setKeyframe -at rotateY -t 101 -v 32.141176470600016 $cameraTransform; 
setKeyframe -at rotateZ -t 101 -v -0.000000000000018 $cameraTransform; 
setKeyframe -at focalLength -t 101 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 102 -v 87.855634205300177 $cameraTransform; 
setKeyframe -at translateY -t 102 -v 100.085249012000418 $cameraTransform; 
setKeyframe -at translateZ -t 102 -v 292.525004566000234 $cameraTransform; 
setKeyframe -at rotateX -t 102 -v -30.635294117600068 $cameraTransform; 
setKeyframe -at rotateY -t 102 -v 32.870588235300005 $cameraTransform; 
setKeyframe -at rotateZ -t 102 -v -0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 102 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 103 -v 89.625229017000180 $cameraTransform; 
setKeyframe -at translateY -t 103 -v 100.488301165000394 $cameraTransform; 
setKeyframe -at translateZ -t 103 -v 296.425334293000219 $cameraTransform; 
setKeyframe -at rotateX -t 103 -v -30.600000000000065 $cameraTransform; 
setKeyframe -at rotateY -t 103 -v 33.600000000000001 $cameraTransform; 
setKeyframe -at rotateZ -t 103 -v 0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 103 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 104 -v 91.395719029600130 $cameraTransform; 
setKeyframe -at translateY -t 104 -v 100.893444873000320 $cameraTransform; 
setKeyframe -at translateZ -t 104 -v 300.324873654000214 $cameraTransform; 
setKeyframe -at rotateX -t 104 -v -30.564705882400034 $cameraTransform; 
setKeyframe -at rotateY -t 104 -v 34.329411764699998 $cameraTransform; 
setKeyframe -at rotateZ -t 104 -v 0.000000000000000 $cameraTransform; 
setKeyframe -at focalLength -t 104 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 105 -v 93.167030090700138 $cameraTransform; 
setKeyframe -at translateY -t 105 -v 101.300582326000310 $cameraTransform; 
setKeyframe -at translateZ -t 105 -v 304.223633716000165 $cameraTransform; 
setKeyframe -at rotateX -t 105 -v -30.529411764700047 $cameraTransform; 
setKeyframe -at rotateY -t 105 -v 35.058823529399994 $cameraTransform; 
setKeyframe -at rotateZ -t 105 -v -0.000000000000015 $cameraTransform; 
setKeyframe -at focalLength -t 105 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 106 -v 94.939088048100174 $cameraTransform; 
setKeyframe -at translateY -t 106 -v 101.709615714000392 $cameraTransform; 
setKeyframe -at translateZ -t 106 -v 308.121625547000292 $cameraTransform; 
setKeyframe -at rotateX -t 106 -v -30.494117647100058 $cameraTransform; 
setKeyframe -at rotateY -t 106 -v 35.788235294099991 $cameraTransform; 
setKeyframe -at rotateZ -t 106 -v -0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 106 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 107 -v 96.711818749500139 $cameraTransform; 
setKeyframe -at translateY -t 107 -v 102.120447229000320 $cameraTransform; 
setKeyframe -at translateZ -t 107 -v 312.018860216000235 $cameraTransform; 
setKeyframe -at rotateX -t 107 -v -30.458823529400036 $cameraTransform; 
setKeyframe -at rotateY -t 107 -v 36.517647058800002 $cameraTransform; 
setKeyframe -at rotateZ -t 107 -v 0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 107 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 108 -v 98.485148042500157 $cameraTransform; 
setKeyframe -at translateY -t 108 -v 102.532979060000400 $cameraTransform; 
setKeyframe -at translateZ -t 108 -v 315.915348790000280 $cameraTransform; 
setKeyframe -at rotateX -t 108 -v -30.423529411800036 $cameraTransform; 
setKeyframe -at rotateY -t 108 -v 37.247058823500012 $cameraTransform; 
setKeyframe -at rotateZ -t 108 -v 0.000000000000000 $cameraTransform; 
setKeyframe -at focalLength -t 108 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 109 -v 100.259001775000172 $cameraTransform; 
setKeyframe -at translateY -t 109 -v 102.947113398000283 $cameraTransform; 
setKeyframe -at translateZ -t 109 -v 319.811102337000193 $cameraTransform; 
setKeyframe -at rotateX -t 109 -v -30.388235294100024 $cameraTransform; 
setKeyframe -at rotateY -t 109 -v 37.976470588200002 $cameraTransform; 
setKeyframe -at rotateZ -t 109 -v 0.000000000000000 $cameraTransform; 
setKeyframe -at focalLength -t 109 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 110 -v 102.033305794000213 $cameraTransform; 
setKeyframe -at translateY -t 110 -v 103.362752434000441 $cameraTransform; 
setKeyframe -at translateZ -t 110 -v 323.706131926000239 $cameraTransform; 
setKeyframe -at rotateX -t 110 -v -30.352941176500046 $cameraTransform; 
setKeyframe -at rotateY -t 110 -v 38.705882352899984 $cameraTransform; 
setKeyframe -at rotateZ -t 110 -v 0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 110 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 111 -v 103.807985948000251 $cameraTransform; 
setKeyframe -at translateY -t 111 -v 103.779798357000431 $cameraTransform; 
setKeyframe -at translateZ -t 111 -v 327.600448624000251 $cameraTransform; 
setKeyframe -at rotateX -t 111 -v -30.317647058800034 $cameraTransform; 
setKeyframe -at rotateY -t 111 -v 39.435294117600009 $cameraTransform; 
setKeyframe -at rotateZ -t 111 -v -0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 111 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 112 -v 105.582968084000200 $cameraTransform; 
setKeyframe -at translateY -t 112 -v 104.198153359000415 $cameraTransform; 
setKeyframe -at translateZ -t 112 -v 331.494063500000209 $cameraTransform; 
setKeyframe -at rotateX -t 112 -v -30.282352941200077 $cameraTransform; 
setKeyframe -at rotateY -t 112 -v 40.164705882400014 $cameraTransform; 
setKeyframe -at rotateZ -t 112 -v -0.000000000000011 $cameraTransform; 
setKeyframe -at focalLength -t 112 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 113 -v 107.358178051000309 $cameraTransform; 
setKeyframe -at translateY -t 113 -v 104.617719630000437 $cameraTransform; 
setKeyframe -at translateZ -t 113 -v 335.386987621000230 $cameraTransform; 
setKeyframe -at rotateX -t 113 -v -30.247058823500055 $cameraTransform; 
setKeyframe -at rotateY -t 113 -v 40.894117647100025 $cameraTransform; 
setKeyframe -at rotateZ -t 113 -v -0.000000000000013 $cameraTransform; 
setKeyframe -at focalLength -t 113 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 114 -v 109.133541695000176 $cameraTransform; 
setKeyframe -at translateY -t 114 -v 105.038399360000412 $cameraTransform; 
setKeyframe -at translateZ -t 114 -v 339.279232055000307 $cameraTransform; 
setKeyframe -at rotateX -t 114 -v -30.211764705900038 $cameraTransform; 
setKeyframe -at rotateY -t 114 -v 41.623529411799993 $cameraTransform; 
setKeyframe -at rotateZ -t 114 -v 0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 114 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 115 -v 110.908984864000246 $cameraTransform; 
setKeyframe -at translateY -t 115 -v 105.460094741000475 $cameraTransform; 
setKeyframe -at translateZ -t 115 -v 343.170807871000306 $cameraTransform; 
setKeyframe -at rotateX -t 115 -v -30.176470588200065 $cameraTransform; 
setKeyframe -at rotateY -t 115 -v 42.352941176499989 $cameraTransform; 
setKeyframe -at rotateZ -t 115 -v 0.000000000000006 $cameraTransform; 
setKeyframe -at focalLength -t 115 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 116 -v 112.684433407000185 $cameraTransform; 
setKeyframe -at translateY -t 116 -v 105.882707961000349 $cameraTransform; 
setKeyframe -at translateZ -t 116 -v 347.061726136000175 $cameraTransform; 
setKeyframe -at rotateX -t 116 -v -30.141176470600062 $cameraTransform; 
setKeyframe -at rotateY -t 116 -v 43.082352941200000 $cameraTransform; 
setKeyframe -at rotateZ -t 116 -v 0.000000000000002 $cameraTransform; 
setKeyframe -at focalLength -t 116 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 117 -v 114.459813170000245 $cameraTransform; 
setKeyframe -at translateY -t 117 -v 106.306141212000426 $cameraTransform; 
setKeyframe -at translateZ -t 117 -v 350.951997918000245 $cameraTransform; 
setKeyframe -at rotateX -t 117 -v -30.105882352900057 $cameraTransform; 
setKeyframe -at rotateY -t 117 -v 43.811764705900011 $cameraTransform; 
setKeyframe -at rotateZ -t 117 -v -0.000000000000011 $cameraTransform; 
setKeyframe -at focalLength -t 117 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 118 -v 116.235050002000321 $cameraTransform; 
setKeyframe -at translateY -t 118 -v 106.730296685000511 $cameraTransform; 
setKeyframe -at translateZ -t 118 -v 354.841634286000215 $cameraTransform; 
setKeyframe -at rotateX -t 118 -v -30.070588235300029 $cameraTransform; 
setKeyframe -at rotateY -t 118 -v 44.541176470600000 $cameraTransform; 
setKeyframe -at rotateZ -t 118 -v -0.000000000000004 $cameraTransform; 
setKeyframe -at focalLength -t 118 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 119 -v 118.010069750000312 $cameraTransform; 
setKeyframe -at translateY -t 119 -v 107.155076569000542 $cameraTransform; 
setKeyframe -at translateZ -t 119 -v 358.730646307000256 $cameraTransform; 
setKeyframe -at rotateX -t 119 -v -30.035294117600056 $cameraTransform; 
setKeyframe -at rotateY -t 119 -v 45.270588235300039 $cameraTransform; 
setKeyframe -at rotateZ -t 119 -v -0.000000000000007 $cameraTransform; 
setKeyframe -at focalLength -t 119 -v 35.000000000000000 $cameraShape;
setKeyframe -at translateX -t 120 -v 119.784798262000308 $cameraTransform; 
setKeyframe -at translateY -t 120 -v 107.580383056000485 $cameraTransform; 
setKeyframe -at translateZ -t 120 -v 362.619045049000306 $cameraTransform; 
setKeyframe -at rotateX -t 120 -v -30.000000000000050 $cameraTransform; 
setKeyframe -at rotateY -t 120 -v 46.000000000000050 $cameraTransform; 
setKeyframe -at rotateZ -t 120 -v -0.000000000000011 $cameraTransform; 
setKeyframe -at focalLength -t 120 -v 35.000000000000000 $cameraShape;

// create camera point group...
string $pointGroupName = `group -em -name  "cameraPGroup_pgroup_1_1" -parent $sceneGroupName`;
$pointGroupName = ($sceneGroupName + "|" + $pointGroupName);


// create point plocator368...
string $locator = stringArrayToString(`spaceLocator -name plocator368`, "");
$locator = ("|" + $locator);
xform -t 187.500000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator370...
string $locator = stringArrayToString(`spaceLocator -name plocator370`, "");
$locator = ("|" + $locator);
xform -t 187.500000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator388...
string $locator = stringArrayToString(`spaceLocator -name plocator388`, "");
$locator = ("|" + $locator);
xform -t 156.250000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator389...
string $locator = stringArrayToString(`spaceLocator -name plocator389`, "");
$locator = ("|" + $locator);
xform -t 156.250000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator390...
string $locator = stringArrayToString(`spaceLocator -name plocator390`, "");
$locator = ("|" + $locator);
xform -t 156.250000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator391...
string $locator = stringArrayToString(`spaceLocator -name plocator391`, "");
$locator = ("|" + $locator);
xform -t 156.250000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator433...
string $locator = stringArrayToString(`spaceLocator -name plocator433`, "");
$locator = ("|" + $locator);
xform -t 125.000000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator434...
string $locator = stringArrayToString(`spaceLocator -name plocator434`, "");
$locator = ("|" + $locator);
xform -t 125.000000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator435...
string $locator = stringArrayToString(`spaceLocator -name plocator435`, "");
$locator = ("|" + $locator);
xform -t 125.000000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator436...
string $locator = stringArrayToString(`spaceLocator -name plocator436`, "");
$locator = ("|" + $locator);
xform -t 125.000000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator437...
string $locator = stringArrayToString(`spaceLocator -name plocator437`, "");
$locator = ("|" + $locator);
xform -t 125.000000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator438...
string $locator = stringArrayToString(`spaceLocator -name plocator438`, "");
$locator = ("|" + $locator);
xform -t 125.000000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator454...
string $locator = stringArrayToString(`spaceLocator -name plocator454`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator455...
string $locator = stringArrayToString(`spaceLocator -name plocator455`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator456...
string $locator = stringArrayToString(`spaceLocator -name plocator456`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator457...
string $locator = stringArrayToString(`spaceLocator -name plocator457`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator458...
string $locator = stringArrayToString(`spaceLocator -name plocator458`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator459...
string $locator = stringArrayToString(`spaceLocator -name plocator459`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator460...
string $locator = stringArrayToString(`spaceLocator -name plocator460`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator461...
string $locator = stringArrayToString(`spaceLocator -name plocator461`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator462...
string $locator = stringArrayToString(`spaceLocator -name plocator462`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator463...
string $locator = stringArrayToString(`spaceLocator -name plocator463`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator478...
string $locator = stringArrayToString(`spaceLocator -name plocator478`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator480...
string $locator = stringArrayToString(`spaceLocator -name plocator480`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator481...
string $locator = stringArrayToString(`spaceLocator -name plocator481`, "");
$locator = ("|" + $locator);
xform -t 93.750000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator495...
string $locator = stringArrayToString(`spaceLocator -name plocator495`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator496...
string $locator = stringArrayToString(`spaceLocator -name plocator496`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator497...
string $locator = stringArrayToString(`spaceLocator -name plocator497`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator498...
string $locator = stringArrayToString(`spaceLocator -name plocator498`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator499...
string $locator = stringArrayToString(`spaceLocator -name plocator499`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator500...
string $locator = stringArrayToString(`spaceLocator -name plocator500`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator501...
string $locator = stringArrayToString(`spaceLocator -name plocator501`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator502...
string $locator = stringArrayToString(`spaceLocator -name plocator502`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator503...
string $locator = stringArrayToString(`spaceLocator -name plocator503`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator508...
string $locator = stringArrayToString(`spaceLocator -name plocator508`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -312.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator509...
string $locator = stringArrayToString(`spaceLocator -name plocator509`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator510...
string $locator = stringArrayToString(`spaceLocator -name plocator510`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator511...
string $locator = stringArrayToString(`spaceLocator -name plocator511`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator512...
string $locator = stringArrayToString(`spaceLocator -name plocator512`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator513...
string $locator = stringArrayToString(`spaceLocator -name plocator513`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator514...
string $locator = stringArrayToString(`spaceLocator -name plocator514`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator515...
string $locator = stringArrayToString(`spaceLocator -name plocator515`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator516...
string $locator = stringArrayToString(`spaceLocator -name plocator516`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator517...
string $locator = stringArrayToString(`spaceLocator -name plocator517`, "");
$locator = ("|" + $locator);
xform -t 62.500000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator529...
string $locator = stringArrayToString(`spaceLocator -name plocator529`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -343.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator530...
string $locator = stringArrayToString(`spaceLocator -name plocator530`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -312.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator531...
string $locator = stringArrayToString(`spaceLocator -name plocator531`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator532...
string $locator = stringArrayToString(`spaceLocator -name plocator532`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator533...
string $locator = stringArrayToString(`spaceLocator -name plocator533`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator534...
string $locator = stringArrayToString(`spaceLocator -name plocator534`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator535...
string $locator = stringArrayToString(`spaceLocator -name plocator535`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator536...
string $locator = stringArrayToString(`spaceLocator -name plocator536`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator537...
string $locator = stringArrayToString(`spaceLocator -name plocator537`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator538...
string $locator = stringArrayToString(`spaceLocator -name plocator538`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator539...
string $locator = stringArrayToString(`spaceLocator -name plocator539`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator540...
string $locator = stringArrayToString(`spaceLocator -name plocator540`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator541...
string $locator = stringArrayToString(`spaceLocator -name plocator541`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator542...
string $locator = stringArrayToString(`spaceLocator -name plocator542`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator543...
string $locator = stringArrayToString(`spaceLocator -name plocator543`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator544...
string $locator = stringArrayToString(`spaceLocator -name plocator544`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator545...
string $locator = stringArrayToString(`spaceLocator -name plocator545`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator546...
string $locator = stringArrayToString(`spaceLocator -name plocator546`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator547...
string $locator = stringArrayToString(`spaceLocator -name plocator547`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator548...
string $locator = stringArrayToString(`spaceLocator -name plocator548`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator549...
string $locator = stringArrayToString(`spaceLocator -name plocator549`, "");
$locator = ("|" + $locator);
xform -t 31.250000000000000 -0.000000000000111 281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator561...
string $locator = stringArrayToString(`spaceLocator -name plocator561`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -375.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator562...
string $locator = stringArrayToString(`spaceLocator -name plocator562`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -343.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator563...
string $locator = stringArrayToString(`spaceLocator -name plocator563`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -312.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator564...
string $locator = stringArrayToString(`spaceLocator -name plocator564`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator565...
string $locator = stringArrayToString(`spaceLocator -name plocator565`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator566...
string $locator = stringArrayToString(`spaceLocator -name plocator566`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator567...
string $locator = stringArrayToString(`spaceLocator -name plocator567`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator568...
string $locator = stringArrayToString(`spaceLocator -name plocator568`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator569...
string $locator = stringArrayToString(`spaceLocator -name plocator569`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator570...
string $locator = stringArrayToString(`spaceLocator -name plocator570`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator571...
string $locator = stringArrayToString(`spaceLocator -name plocator571`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator572...
string $locator = stringArrayToString(`spaceLocator -name plocator572`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator573...
string $locator = stringArrayToString(`spaceLocator -name plocator573`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator574...
string $locator = stringArrayToString(`spaceLocator -name plocator574`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator575...
string $locator = stringArrayToString(`spaceLocator -name plocator575`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator576...
string $locator = stringArrayToString(`spaceLocator -name plocator576`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator577...
string $locator = stringArrayToString(`spaceLocator -name plocator577`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator578...
string $locator = stringArrayToString(`spaceLocator -name plocator578`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator579...
string $locator = stringArrayToString(`spaceLocator -name plocator579`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator580...
string $locator = stringArrayToString(`spaceLocator -name plocator580`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator581...
string $locator = stringArrayToString(`spaceLocator -name plocator581`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator582...
string $locator = stringArrayToString(`spaceLocator -name plocator582`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator583...
string $locator = stringArrayToString(`spaceLocator -name plocator583`, "");
$locator = ("|" + $locator);
xform -t 0.000000000000000 -0.000000000000111 312.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator595...
string $locator = stringArrayToString(`spaceLocator -name plocator595`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -343.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator596...
string $locator = stringArrayToString(`spaceLocator -name plocator596`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -312.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator597...
string $locator = stringArrayToString(`spaceLocator -name plocator597`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator598...
string $locator = stringArrayToString(`spaceLocator -name plocator598`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator599...
string $locator = stringArrayToString(`spaceLocator -name plocator599`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator600...
string $locator = stringArrayToString(`spaceLocator -name plocator600`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator601...
string $locator = stringArrayToString(`spaceLocator -name plocator601`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator602...
string $locator = stringArrayToString(`spaceLocator -name plocator602`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator603...
string $locator = stringArrayToString(`spaceLocator -name plocator603`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator604...
string $locator = stringArrayToString(`spaceLocator -name plocator604`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator605...
string $locator = stringArrayToString(`spaceLocator -name plocator605`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 312.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator611...
string $locator = stringArrayToString(`spaceLocator -name plocator611`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator612...
string $locator = stringArrayToString(`spaceLocator -name plocator612`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator613...
string $locator = stringArrayToString(`spaceLocator -name plocator613`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator614...
string $locator = stringArrayToString(`spaceLocator -name plocator614`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator615...
string $locator = stringArrayToString(`spaceLocator -name plocator615`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator616...
string $locator = stringArrayToString(`spaceLocator -name plocator616`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator617...
string $locator = stringArrayToString(`spaceLocator -name plocator617`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator618...
string $locator = stringArrayToString(`spaceLocator -name plocator618`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator619...
string $locator = stringArrayToString(`spaceLocator -name plocator619`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator620...
string $locator = stringArrayToString(`spaceLocator -name plocator620`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator621...
string $locator = stringArrayToString(`spaceLocator -name plocator621`, "");
$locator = ("|" + $locator);
xform -t -31.250000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator622...
string $locator = stringArrayToString(`spaceLocator -name plocator622`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator623...
string $locator = stringArrayToString(`spaceLocator -name plocator623`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator624...
string $locator = stringArrayToString(`spaceLocator -name plocator624`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator625...
string $locator = stringArrayToString(`spaceLocator -name plocator625`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator626...
string $locator = stringArrayToString(`spaceLocator -name plocator626`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator627...
string $locator = stringArrayToString(`spaceLocator -name plocator627`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator628...
string $locator = stringArrayToString(`spaceLocator -name plocator628`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator629...
string $locator = stringArrayToString(`spaceLocator -name plocator629`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator630...
string $locator = stringArrayToString(`spaceLocator -name plocator630`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator631...
string $locator = stringArrayToString(`spaceLocator -name plocator631`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator632...
string $locator = stringArrayToString(`spaceLocator -name plocator632`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator641...
string $locator = stringArrayToString(`spaceLocator -name plocator641`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator642...
string $locator = stringArrayToString(`spaceLocator -name plocator642`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator643...
string $locator = stringArrayToString(`spaceLocator -name plocator643`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator644...
string $locator = stringArrayToString(`spaceLocator -name plocator644`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator645...
string $locator = stringArrayToString(`spaceLocator -name plocator645`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator646...
string $locator = stringArrayToString(`spaceLocator -name plocator646`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator647...
string $locator = stringArrayToString(`spaceLocator -name plocator647`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator648...
string $locator = stringArrayToString(`spaceLocator -name plocator648`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator649...
string $locator = stringArrayToString(`spaceLocator -name plocator649`, "");
$locator = ("|" + $locator);
xform -t -62.500000000000000 -0.000000000000111 312.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator661...
string $locator = stringArrayToString(`spaceLocator -name plocator661`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator662...
string $locator = stringArrayToString(`spaceLocator -name plocator662`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator663...
string $locator = stringArrayToString(`spaceLocator -name plocator663`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator664...
string $locator = stringArrayToString(`spaceLocator -name plocator664`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator665...
string $locator = stringArrayToString(`spaceLocator -name plocator665`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator666...
string $locator = stringArrayToString(`spaceLocator -name plocator666`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator667...
string $locator = stringArrayToString(`spaceLocator -name plocator667`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator668...
string $locator = stringArrayToString(`spaceLocator -name plocator668`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator669...
string $locator = stringArrayToString(`spaceLocator -name plocator669`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator676...
string $locator = stringArrayToString(`spaceLocator -name plocator676`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 -250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator677...
string $locator = stringArrayToString(`spaceLocator -name plocator677`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 -218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator678...
string $locator = stringArrayToString(`spaceLocator -name plocator678`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator679...
string $locator = stringArrayToString(`spaceLocator -name plocator679`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator680...
string $locator = stringArrayToString(`spaceLocator -name plocator680`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator681...
string $locator = stringArrayToString(`spaceLocator -name plocator681`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator682...
string $locator = stringArrayToString(`spaceLocator -name plocator682`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator683...
string $locator = stringArrayToString(`spaceLocator -name plocator683`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator684...
string $locator = stringArrayToString(`spaceLocator -name plocator684`, "");
$locator = ("|" + $locator);
xform -t -93.750000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator699...
string $locator = stringArrayToString(`spaceLocator -name plocator699`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 -187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator700...
string $locator = stringArrayToString(`spaceLocator -name plocator700`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 -156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator701...
string $locator = stringArrayToString(`spaceLocator -name plocator701`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator702...
string $locator = stringArrayToString(`spaceLocator -name plocator702`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator703...
string $locator = stringArrayToString(`spaceLocator -name plocator703`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator704...
string $locator = stringArrayToString(`spaceLocator -name plocator704`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator705...
string $locator = stringArrayToString(`spaceLocator -name plocator705`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator706...
string $locator = stringArrayToString(`spaceLocator -name plocator706`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator707...
string $locator = stringArrayToString(`spaceLocator -name plocator707`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator708...
string $locator = stringArrayToString(`spaceLocator -name plocator708`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator709...
string $locator = stringArrayToString(`spaceLocator -name plocator709`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator710...
string $locator = stringArrayToString(`spaceLocator -name plocator710`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator711...
string $locator = stringArrayToString(`spaceLocator -name plocator711`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator712...
string $locator = stringArrayToString(`spaceLocator -name plocator712`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator713...
string $locator = stringArrayToString(`spaceLocator -name plocator713`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator714...
string $locator = stringArrayToString(`spaceLocator -name plocator714`, "");
$locator = ("|" + $locator);
xform -t -125.000000000000000 -0.000000000000111 281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator722...
string $locator = stringArrayToString(`spaceLocator -name plocator722`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 -125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator723...
string $locator = stringArrayToString(`spaceLocator -name plocator723`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator724...
string $locator = stringArrayToString(`spaceLocator -name plocator724`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator725...
string $locator = stringArrayToString(`spaceLocator -name plocator725`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator726...
string $locator = stringArrayToString(`spaceLocator -name plocator726`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator727...
string $locator = stringArrayToString(`spaceLocator -name plocator727`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator728...
string $locator = stringArrayToString(`spaceLocator -name plocator728`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator729...
string $locator = stringArrayToString(`spaceLocator -name plocator729`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator730...
string $locator = stringArrayToString(`spaceLocator -name plocator730`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator743...
string $locator = stringArrayToString(`spaceLocator -name plocator743`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator744...
string $locator = stringArrayToString(`spaceLocator -name plocator744`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator745...
string $locator = stringArrayToString(`spaceLocator -name plocator745`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator746...
string $locator = stringArrayToString(`spaceLocator -name plocator746`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator747...
string $locator = stringArrayToString(`spaceLocator -name plocator747`, "");
$locator = ("|" + $locator);
xform -t -156.250000000000000 -0.000000000000111 281.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator770...
string $locator = stringArrayToString(`spaceLocator -name plocator770`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator771...
string $locator = stringArrayToString(`spaceLocator -name plocator771`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator772...
string $locator = stringArrayToString(`spaceLocator -name plocator772`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator773...
string $locator = stringArrayToString(`spaceLocator -name plocator773`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator774...
string $locator = stringArrayToString(`spaceLocator -name plocator774`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator775...
string $locator = stringArrayToString(`spaceLocator -name plocator775`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator776...
string $locator = stringArrayToString(`spaceLocator -name plocator776`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator777...
string $locator = stringArrayToString(`spaceLocator -name plocator777`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator778...
string $locator = stringArrayToString(`spaceLocator -name plocator778`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator779...
string $locator = stringArrayToString(`spaceLocator -name plocator779`, "");
$locator = ("|" + $locator);
xform -t -187.500000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator801...
string $locator = stringArrayToString(`spaceLocator -name plocator801`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 -93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator802...
string $locator = stringArrayToString(`spaceLocator -name plocator802`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator804...
string $locator = stringArrayToString(`spaceLocator -name plocator804`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator805...
string $locator = stringArrayToString(`spaceLocator -name plocator805`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator806...
string $locator = stringArrayToString(`spaceLocator -name plocator806`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator807...
string $locator = stringArrayToString(`spaceLocator -name plocator807`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator808...
string $locator = stringArrayToString(`spaceLocator -name plocator808`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator809...
string $locator = stringArrayToString(`spaceLocator -name plocator809`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator810...
string $locator = stringArrayToString(`spaceLocator -name plocator810`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator811...
string $locator = stringArrayToString(`spaceLocator -name plocator811`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator812...
string $locator = stringArrayToString(`spaceLocator -name plocator812`, "");
$locator = ("|" + $locator);
xform -t -218.750000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator823...
string $locator = stringArrayToString(`spaceLocator -name plocator823`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 -62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator824...
string $locator = stringArrayToString(`spaceLocator -name plocator824`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator839...
string $locator = stringArrayToString(`spaceLocator -name plocator839`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator840...
string $locator = stringArrayToString(`spaceLocator -name plocator840`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator841...
string $locator = stringArrayToString(`spaceLocator -name plocator841`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator842...
string $locator = stringArrayToString(`spaceLocator -name plocator842`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator843...
string $locator = stringArrayToString(`spaceLocator -name plocator843`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator844...
string $locator = stringArrayToString(`spaceLocator -name plocator844`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator845...
string $locator = stringArrayToString(`spaceLocator -name plocator845`, "");
$locator = ("|" + $locator);
xform -t -250.000000000000000 -0.000000000000111 250.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator869...
string $locator = stringArrayToString(`spaceLocator -name plocator869`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 -31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator870...
string $locator = stringArrayToString(`spaceLocator -name plocator870`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator871...
string $locator = stringArrayToString(`spaceLocator -name plocator871`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator872...
string $locator = stringArrayToString(`spaceLocator -name plocator872`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator873...
string $locator = stringArrayToString(`spaceLocator -name plocator873`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 93.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator874...
string $locator = stringArrayToString(`spaceLocator -name plocator874`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 125.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator875...
string $locator = stringArrayToString(`spaceLocator -name plocator875`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator876...
string $locator = stringArrayToString(`spaceLocator -name plocator876`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator877...
string $locator = stringArrayToString(`spaceLocator -name plocator877`, "");
$locator = ("|" + $locator);
xform -t -281.250000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator903...
string $locator = stringArrayToString(`spaceLocator -name plocator903`, "");
$locator = ("|" + $locator);
xform -t -312.500000000000000 -0.000000000000111 0.000000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator904...
string $locator = stringArrayToString(`spaceLocator -name plocator904`, "");
$locator = ("|" + $locator);
xform -t -312.500000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator905...
string $locator = stringArrayToString(`spaceLocator -name plocator905`, "");
$locator = ("|" + $locator);
xform -t -312.500000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator908...
string $locator = stringArrayToString(`spaceLocator -name plocator908`, "");
$locator = ("|" + $locator);
xform -t -312.500000000000000 -0.000000000000111 156.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator909...
string $locator = stringArrayToString(`spaceLocator -name plocator909`, "");
$locator = ("|" + $locator);
xform -t -312.500000000000000 -0.000000000000111 187.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator910...
string $locator = stringArrayToString(`spaceLocator -name plocator910`, "");
$locator = ("|" + $locator);
xform -t -312.500000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator937...
string $locator = stringArrayToString(`spaceLocator -name plocator937`, "");
$locator = ("|" + $locator);
xform -t -343.750000000000000 -0.000000000000111 31.250000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator938...
string $locator = stringArrayToString(`spaceLocator -name plocator938`, "");
$locator = ("|" + $locator);
xform -t -343.750000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator943...
string $locator = stringArrayToString(`spaceLocator -name plocator943`, "");
$locator = ("|" + $locator);
xform -t -343.750000000000000 -0.000000000000111 218.750000000000000 $locator;
parent $locator $pointGroupName;

// create point plocator959...
string $locator = stringArrayToString(`spaceLocator -name plocator959`, "");
$locator = ("|" + $locator);
xform -t -375.000000000000000 -0.000000000000111 62.500000000000000 $locator;
parent $locator $pointGroupName;

xform -zeroTransformPivots -rotateOrder zxy -scale 1.000000 1.000000 1.000000 $pointGroupName;


// create object point group...
string $pointGroupName = `group -em -name  "objectPGroup_pgroup_3_1_1" -parent $sceneGroupName`;
$pointGroupName = ($sceneGroupName + "|" + $pointGroupName);

// create point p01...
string $locator = stringArrayToString(`spaceLocator -name p01`, "");
$locator = ("|" + $locator);
xform -t -14.999998000000000 18.867075000000000 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p02...
string $locator = stringArrayToString(`spaceLocator -name p02`, "");
$locator = ("|" + $locator);
xform -t -11.873581000000000 18.867075000000000 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p03...
string $locator = stringArrayToString(`spaceLocator -name p03`, "");
$locator = ("|" + $locator);
xform -t -11.873581000000000 15.740657000000001 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p04...
string $locator = stringArrayToString(`spaceLocator -name p04`, "");
$locator = ("|" + $locator);
xform -t 11.873582000000001 15.740655000000000 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p05...
string $locator = stringArrayToString(`spaceLocator -name p05`, "");
$locator = ("|" + $locator);
xform -t 11.873582000000001 18.867073000000001 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p06...
string $locator = stringArrayToString(`spaceLocator -name p06`, "");
$locator = ("|" + $locator);
xform -t 14.999999000000001 18.867073000000001 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p07...
string $locator = stringArrayToString(`spaceLocator -name p07`, "");
$locator = ("|" + $locator);
xform -t 15.000000000000000 15.740656000000000 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p08...
string $locator = stringArrayToString(`spaceLocator -name p08`, "");
$locator = ("|" + $locator);
xform -t 15.000000000000000 7.171637000000000 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p09...
string $locator = stringArrayToString(`spaceLocator -name p09`, "");
$locator = ("|" + $locator);
xform -t 15.000000000000000 7.171637000000000 18.601295000000000 $locator;
parent $locator $pointGroupName;

// create point p10...
string $locator = stringArrayToString(`spaceLocator -name p10`, "");
$locator = ("|" + $locator);
xform -t 15.000000000000000 7.171637000000000 -18.601295000000000 $locator;
parent $locator $pointGroupName;

// create point p11...
string $locator = stringArrayToString(`spaceLocator -name p11`, "");
$locator = ("|" + $locator);
xform -t 15.000000000000000 7.171637000000000 -35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p12...
string $locator = stringArrayToString(`spaceLocator -name p12`, "");
$locator = ("|" + $locator);
xform -t 15.000000000000000 15.740656000000000 -35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p13...
string $locator = stringArrayToString(`spaceLocator -name p13`, "");
$locator = ("|" + $locator);
xform -t 15.000000000000000 15.740653999999999 -18.601295000000000 $locator;
parent $locator $pointGroupName;

// create point p14...
string $locator = stringArrayToString(`spaceLocator -name p14`, "");
$locator = ("|" + $locator);
xform -t 10.977759000000001 30.740653999999999 -10.151496000000000 $locator;
parent $locator $pointGroupName;

// create point p15...
string $locator = stringArrayToString(`spaceLocator -name p15`, "");
$locator = ("|" + $locator);
xform -t 10.977759000000001 30.740653999999999 10.151496000000000 $locator;
parent $locator $pointGroupName;

// create point p16...
string $locator = stringArrayToString(`spaceLocator -name p16`, "");
$locator = ("|" + $locator);
xform -t 15.000000000000000 15.740653999999999 18.601295000000000 $locator;
parent $locator $pointGroupName;

// create point p17...
string $locator = stringArrayToString(`spaceLocator -name p17`, "");
$locator = ("|" + $locator);
xform -t 14.999999000000001 15.740655000000000 31.873588999999999 $locator;
parent $locator $pointGroupName;

// create point p18...
string $locator = stringArrayToString(`spaceLocator -name p18`, "");
$locator = ("|" + $locator);
xform -t 14.999999000000001 18.867073000000001 31.873588999999999 $locator;
parent $locator $pointGroupName;

// create point p19...
string $locator = stringArrayToString(`spaceLocator -name p19`, "");
$locator = ("|" + $locator);
xform -t 11.873582000000001 18.867073000000001 31.873588999999999 $locator;
parent $locator $pointGroupName;

// create point p20...
string $locator = stringArrayToString(`spaceLocator -name p20`, "");
$locator = ("|" + $locator);
xform -t 11.873582000000001 15.740655000000000 31.873588999999999 $locator;
parent $locator $pointGroupName;

// create point p21...
string $locator = stringArrayToString(`spaceLocator -name p21`, "");
$locator = ("|" + $locator);
xform -t -11.873581000000000 15.740657000000001 31.873588999999999 $locator;
parent $locator $pointGroupName;

// create point p22...
string $locator = stringArrayToString(`spaceLocator -name p22`, "");
$locator = ("|" + $locator);
xform -t -11.873581000000000 18.867075000000000 31.873588999999999 $locator;
parent $locator $pointGroupName;

// create point p23...
string $locator = stringArrayToString(`spaceLocator -name p23`, "");
$locator = ("|" + $locator);
xform -t -14.999998000000000 18.867075000000000 31.873588999999999 $locator;
parent $locator $pointGroupName;

// create point p24...
string $locator = stringArrayToString(`spaceLocator -name p24`, "");
$locator = ("|" + $locator);
xform -t -14.999998000000000 15.740657000000001 31.873588999999999 $locator;
parent $locator $pointGroupName;

// create point p25...
string $locator = stringArrayToString(`spaceLocator -name p25`, "");
$locator = ("|" + $locator);
xform -t -15.000000000000000 15.740656000000000 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p26...
string $locator = stringArrayToString(`spaceLocator -name p26`, "");
$locator = ("|" + $locator);
xform -t -15.000000000000000 7.171637000000000 35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p27...
string $locator = stringArrayToString(`spaceLocator -name p27`, "");
$locator = ("|" + $locator);
xform -t -15.000000000000000 7.171637000000000 18.601295000000000 $locator;
parent $locator $pointGroupName;

// create point p28...
string $locator = stringArrayToString(`spaceLocator -name p28`, "");
$locator = ("|" + $locator);
xform -t -15.000000000000000 7.171637000000000 -18.601295000000000 $locator;
parent $locator $pointGroupName;

// create point p29...
string $locator = stringArrayToString(`spaceLocator -name p29`, "");
$locator = ("|" + $locator);
xform -t -15.000000000000000 7.171637000000000 -35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p30...
string $locator = stringArrayToString(`spaceLocator -name p30`, "");
$locator = ("|" + $locator);
xform -t -15.000000000000000 15.740656000000000 -35.000008000000001 $locator;
parent $locator $pointGroupName;

// create point p31...
string $locator = stringArrayToString(`spaceLocator -name p31`, "");
$locator = ("|" + $locator);
xform -t -15.000000000000000 15.740653999999999 -18.601295000000000 $locator;
parent $locator $pointGroupName;

// create point p32...
string $locator = stringArrayToString(`spaceLocator -name p32`, "");
$locator = ("|" + $locator);
xform -t -10.977759000000001 30.740653999999999 -10.151496000000000 $locator;
parent $locator $pointGroupName;

// create point p33...
string $locator = stringArrayToString(`spaceLocator -name p33`, "");
$locator = ("|" + $locator);
xform -t -10.977759000000001 30.740653999999999 10.151496000000000 $locator;
parent $locator $pointGroupName;

// create point p34...
string $locator = stringArrayToString(`spaceLocator -name p34`, "");
$locator = ("|" + $locator);
xform -t -15.000000000000000 15.740653999999999 18.601295000000000 $locator;
parent $locator $pointGroupName;

// create point p42...
string $locator = stringArrayToString(`spaceLocator -name p42`, "");
$locator = ("|" + $locator);
xform -t 14.021655000000001 -0.002460000000000 22.493271000000000 $locator;
parent $locator $pointGroupName;

// create point p43...
string $locator = stringArrayToString(`spaceLocator -name p43`, "");
$locator = ("|" + $locator);
xform -t 14.021655000000001 -0.002460000000000 -22.493271000000000 $locator;
parent $locator $pointGroupName;

// create point p44...
string $locator = stringArrayToString(`spaceLocator -name p44`, "");
$locator = ("|" + $locator);
xform -t -14.021655000000001 -0.002460000000000 22.493271000000000 $locator;
parent $locator $pointGroupName;

// create point p45...
string $locator = stringArrayToString(`spaceLocator -name p45`, "");
$locator = ("|" + $locator);
xform -t -14.021655000000001 -0.002460000000000 -22.493271000000000 $locator;
parent $locator $pointGroupName;

xform -zeroTransformPivots -rotateOrder zxy -scale 1.000000000000000 1.000000000000000 1.000000000000000 $pointGroupName;

// animating point group objectPGroup_pgroup_3_1_1...
setKeyframe -at translateX -t 1 -v 0.000000000000242 $pointGroupName; 
setKeyframe -at translateY -t 1 -v -0.000000000000242 $pointGroupName; 
setKeyframe -at translateZ -t 1 -v -200.000000000000284 $pointGroupName; 
setKeyframe -at rotateX -t 1 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 1 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 1 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 2 -v -0.001054816761680 $pointGroupName; 
setKeyframe -at translateY -t 2 -v 0.001063224506922 $pointGroupName; 
setKeyframe -at translateZ -t 2 -v -196.637543749932661 $pointGroupName; 
setKeyframe -at rotateX -t 2 -v 0.000019275612127 $pointGroupName; 
setKeyframe -at rotateY -t 2 -v 0.000014737277156 $pointGroupName; 
setKeyframe -at rotateZ -t 2 -v 0.000003449828097 $pointGroupName;
setKeyframe -at translateX -t 3 -v -0.001181724226967 $pointGroupName; 
setKeyframe -at translateY -t 3 -v 0.001211034276864 $pointGroupName; 
setKeyframe -at translateZ -t 3 -v -193.276030968502710 $pointGroupName; 
setKeyframe -at rotateX -t 3 -v 0.000022263278380 $pointGroupName; 
setKeyframe -at rotateY -t 3 -v 0.000016711305461 $pointGroupName; 
setKeyframe -at rotateZ -t 3 -v 0.000003903619169 $pointGroupName;
setKeyframe -at translateX -t 4 -v -0.001012710790405 $pointGroupName; 
setKeyframe -at translateY -t 4 -v 0.001055636962107 $pointGroupName; 
setKeyframe -at translateZ -t 4 -v -189.914838696726491 $pointGroupName; 
setKeyframe -at rotateX -t 4 -v 0.000019688410380 $pointGroupName; 
setKeyframe -at rotateY -t 4 -v 0.000014502507743 $pointGroupName; 
setKeyframe -at rotateZ -t 4 -v 0.000003380649877 $pointGroupName;
setKeyframe -at translateX -t 5 -v -0.000793847250165 $pointGroupName; 
setKeyframe -at translateY -t 5 -v 0.000842095412395 $pointGroupName; 
setKeyframe -at translateZ -t 5 -v -186.553712697874715 $pointGroupName; 
setKeyframe -at rotateX -t 5 -v 0.000015904992203 $pointGroupName; 
setKeyframe -at rotateY -t 5 -v 0.000011491248911 $pointGroupName; 
setKeyframe -at rotateZ -t 5 -v 0.000002673287886 $pointGroupName;
setKeyframe -at translateX -t 6 -v -0.000586506783520 $pointGroupName; 
setKeyframe -at translateY -t 6 -v 0.000633445644027 $pointGroupName; 
setKeyframe -at translateZ -t 6 -v -183.192586205559792 $pointGroupName; 
setKeyframe -at rotateX -t 6 -v 0.000012118608343 $pointGroupName; 
setKeyframe -at rotateY -t 6 -v 0.000008583583906 $pointGroupName; 
setKeyframe -at rotateZ -t 6 -v 0.000001992909916 $pointGroupName;
setKeyframe -at translateX -t 7 -v -0.000400377460991 $pointGroupName; 
setKeyframe -at translateY -t 7 -v 0.000440499756678 $pointGroupName; 
setKeyframe -at translateZ -t 7 -v -179.831447150056988 $pointGroupName; 
setKeyframe -at rotateX -t 7 -v 0.000008573001102 $pointGroupName; 
setKeyframe -at rotateY -t 7 -v 0.000005949793524 $pointGroupName; 
setKeyframe -at rotateZ -t 7 -v 0.000001378725881 $pointGroupName;
setKeyframe -at translateX -t 8 -v -0.000236322433096 $pointGroupName; 
setKeyframe -at translateY -t 8 -v 0.000265008762327 $pointGroupName; 
setKeyframe -at translateZ -t 8 -v -176.470293054031004 $pointGroupName; 
setKeyframe -at rotateX -t 8 -v 0.000005240052864 $pointGroupName; 
setKeyframe -at rotateY -t 8 -v 0.000003561379713 $pointGroupName; 
setKeyframe -at rotateZ -t 8 -v 0.000000823692519 $pointGroupName;
setKeyframe -at translateX -t 9 -v -0.000094143187660 $pointGroupName; 
setKeyframe -at translateY -t 9 -v 0.000107665207864 $pointGroupName; 
setKeyframe -at translateZ -t 9 -v -173.109122544850379 $pointGroupName; 
setKeyframe -at rotateX -t 9 -v 0.000001994399801 $pointGroupName; 
setKeyframe -at rotateY -t 9 -v 0.000001326654253 $pointGroupName; 
setKeyframe -at rotateZ -t 9 -v 0.000000306257164 $pointGroupName;
setKeyframe -at translateX -t 10 -v 0.000026612504541 $pointGroupName; 
setKeyframe -at translateY -t 10 -v -0.000031057657452 $pointGroupName; 
setKeyframe -at translateZ -t 10 -v -169.747934462328118 $pointGroupName; 
setKeyframe -at rotateX -t 10 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 10 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 10 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 11 -v 0.000127022396207 $pointGroupName; 
setKeyframe -at translateY -t 11 -v -0.000151369785129 $pointGroupName; 
setKeyframe -at translateZ -t 11 -v -166.386728405087410 $pointGroupName; 
setKeyframe -at rotateX -t 11 -v -0.000003033413152 $pointGroupName; 
setKeyframe -at rotateY -t 11 -v -0.000001929311276 $pointGroupName; 
setKeyframe -at rotateZ -t 11 -v -0.000000443725706 $pointGroupName;
setKeyframe -at translateX -t 12 -v 0.000210747260958 $pointGroupName; 
setKeyframe -at translateY -t 12 -v -0.000256620574461 $pointGroupName; 
setKeyframe -at translateZ -t 12 -v -163.025507619145031 $pointGroupName; 
setKeyframe -at rotateX -t 12 -v -0.000005290422787 $pointGroupName; 
setKeyframe -at rotateY -t 12 -v -0.000003286978254 $pointGroupName; 
setKeyframe -at rotateZ -t 12 -v -0.000000754579457 $pointGroupName;
setKeyframe -at translateX -t 13 -v 0.000287695258336 $pointGroupName; 
setKeyframe -at translateY -t 13 -v -0.000358215112414 $pointGroupName; 
setKeyframe -at translateZ -t 13 -v -159.664284932332123 $pointGroupName; 
setKeyframe -at rotateX -t 13 -v -0.000007392557414 $pointGroupName; 
setKeyframe -at rotateY -t 13 -v -0.000004483662231 $pointGroupName; 
setKeyframe -at rotateZ -t 13 -v -0.000001027389376 $pointGroupName;
setKeyframe -at translateX -t 14 -v 0.000373248501475 $pointGroupName; 
setKeyframe -at translateY -t 14 -v -0.000475575556749 $pointGroupName; 
setKeyframe -at translateZ -t 14 -v -156.303083163691952 $pointGroupName; 
setKeyframe -at rotateX -t 14 -v -0.000009900460087 $pointGroupName; 
setKeyframe -at rotateY -t 14 -v -0.000005857405730 $pointGroupName; 
setKeyframe -at rotateZ -t 14 -v -0.000001339665467 $pointGroupName;
setKeyframe -at translateX -t 15 -v 0.000368259239494 $pointGroupName; 
setKeyframe -at translateY -t 15 -v -0.000480543700888 $pointGroupName; 
setKeyframe -at translateZ -t 15 -v -152.941749896610048 $pointGroupName; 
setKeyframe -at rotateX -t 15 -v -0.000010129150916 $pointGroupName; 
setKeyframe -at rotateY -t 15 -v -0.000005841135876 $pointGroupName; 
setKeyframe -at rotateZ -t 15 -v -0.000001333426187 $pointGroupName;
setKeyframe -at translateX -t 16 -v 0.000344704016847 $pointGroupName; 
setKeyframe -at translateY -t 16 -v -0.000461053529619 $pointGroupName; 
setKeyframe -at translateZ -t 16 -v -149.580387251878790 $pointGroupName; 
setKeyframe -at rotateX -t 16 -v -0.000009758864704 $pointGroupName; 
setKeyframe -at rotateY -t 16 -v -0.000005480771550 $pointGroupName; 
setKeyframe -at rotateZ -t 16 -v -0.000001248769033 $pointGroupName;
setKeyframe -at translateX -t 17 -v 0.000320359442298 $pointGroupName; 
setKeyframe -at translateY -t 17 -v -0.000439600784645 $pointGroupName; 
setKeyframe -at translateZ -t 17 -v -146.219021754307761 $pointGroupName; 
setKeyframe -at rotateX -t 17 -v -0.000009361760208 $pointGroupName; 
setKeyframe -at rotateY -t 17 -v -0.000005116127290 $pointGroupName; 
setKeyframe -at rotateZ -t 17 -v -0.000001163416401 $pointGroupName;
setKeyframe -at translateX -t 18 -v 0.000285249307808 $pointGroupName; 
setKeyframe -at translateY -t 18 -v -0.000401953388092 $pointGroupName; 
setKeyframe -at translateZ -t 18 -v -142.857635882313843 $pointGroupName; 
setKeyframe -at rotateX -t 18 -v -0.000008613768634 $pointGroupName; 
setKeyframe -at rotateY -t 18 -v -0.000004576350864 $pointGroupName; 
setKeyframe -at rotateZ -t 18 -v -0.000001038599011 $pointGroupName;
setKeyframe -at translateX -t 19 -v 0.000235883511223 $pointGroupName; 
setKeyframe -at translateY -t 19 -v -0.000341679819385 $pointGroupName; 
setKeyframe -at translateZ -t 19 -v -139.496221147593189 $pointGroupName; 
setKeyframe -at rotateX -t 19 -v -0.000007394164191 $pointGroupName; 
setKeyframe -at rotateY -t 19 -v -0.000003815344622 $pointGroupName; 
setKeyframe -at rotateZ -t 19 -v -0.000000864122117 $pointGroupName;
setKeyframe -at translateX -t 20 -v 0.000172290189376 $pointGroupName; 
setKeyframe -at translateY -t 20 -v -0.000256816021434 $pointGroupName; 
setKeyframe -at translateZ -t 20 -v -136.134774370623347 $pointGroupName; 
setKeyframe -at rotateX -t 20 -v -0.000005684098421 $pointGroupName; 
setKeyframe -at rotateY -t 20 -v -0.000002845601739 $pointGroupName; 
setKeyframe -at rotateZ -t 20 -v -0.000000643136278 $pointGroupName;
setKeyframe -at translateX -t 21 -v 0.000095605957469 $pointGroupName; 
setKeyframe -at translateY -t 21 -v -0.000146820587830 $pointGroupName; 
setKeyframe -at translateZ -t 21 -v -132.773294095721837 $pointGroupName; 
setKeyframe -at rotateX -t 21 -v -0.000003057773582 $pointGroupName; 
setKeyframe -at rotateY -t 21 -v -0.000001483560388 $pointGroupName; 
setKeyframe -at rotateZ -t 21 -v -0.000000334574795 $pointGroupName;
setKeyframe -at translateX -t 22 -v 0.000007320920865 $pointGroupName; 
setKeyframe -at translateY -t 22 -v -0.000011596938975 $pointGroupName; 
setKeyframe -at translateZ -t 22 -v -129.411779429627018 $pointGroupName; 
setKeyframe -at rotateX -t 22 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 22 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 22 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 23 -v -0.000090825740891 $pointGroupName; 
setKeyframe -at translateY -t 23 -v 0.000148605774868 $pointGroupName; 
setKeyframe -at translateZ -t 23 -v -126.050229941300842 $pointGroupName; 
setKeyframe -at rotateX -t 23 -v 0.000003284087908 $pointGroupName; 
setKeyframe -at rotateY -t 23 -v 0.000001491119879 $pointGroupName; 
setKeyframe -at rotateZ -t 23 -v 0.000000334750729 $pointGroupName;
setKeyframe -at translateX -t 24 -v -0.000196719765306 $pointGroupName; 
setKeyframe -at translateY -t 24 -v 0.000332919766180 $pointGroupName; 
setKeyframe -at translateZ -t 24 -v -122.688646034837092 $pointGroupName; 
setKeyframe -at rotateX -t 24 -v 0.000007388364549 $pointGroupName; 
setKeyframe -at rotateY -t 24 -v 0.000003238764307 $pointGroupName; 
setKeyframe -at rotateZ -t 24 -v 0.000000725344643 $pointGroupName;
setKeyframe -at translateX -t 25 -v -0.000307313065434 $pointGroupName; 
setKeyframe -at translateY -t 25 -v 0.000538766221155 $pointGroupName; 
setKeyframe -at translateZ -t 25 -v -119.327030403932326 $pointGroupName; 
setKeyframe -at rotateX -t 25 -v 0.000011984872547 $pointGroupName; 
setKeyframe -at rotateY -t 25 -v 0.000005064789957 $pointGroupName; 
setKeyframe -at rotateZ -t 25 -v 0.000001131469230 $pointGroupName;
setKeyframe -at translateX -t 26 -v -0.000417655030418 $pointGroupName; 
setKeyframe -at translateY -t 26 -v 0.000759766962176 $pointGroupName; 
setKeyframe -at translateZ -t 26 -v -115.965390855984182 $pointGroupName; 
setKeyframe -at rotateX -t 26 -v 0.000016975756734 $pointGroupName; 
setKeyframe -at rotateY -t 26 -v 0.000006905048532 $pointGroupName; 
setKeyframe -at rotateZ -t 26 -v 0.000001538587296 $pointGroupName;
setKeyframe -at translateX -t 27 -v -0.000521036742022 $pointGroupName; 
setKeyframe -at translateY -t 27 -v 0.000985256238380 $pointGroupName; 
setKeyframe -at translateZ -t 27 -v -112.603741140688655 $pointGroupName; 
setKeyframe -at rotateX -t 27 -v 0.000022079445847 $pointGroupName; 
setKeyframe -at rotateY -t 27 -v 0.000008629590918 $pointGroupName; 
setKeyframe -at rotateZ -t 27 -v 0.000001917676352 $pointGroupName;
setKeyframe -at translateX -t 28 -v -0.000637822129583 $pointGroupName; 
setKeyframe -at translateY -t 28 -v 0.001256146334967 $pointGroupName; 
setKeyframe -at translateZ -t 28 -v -109.242026847920798 $pointGroupName; 
setKeyframe -at rotateX -t 28 -v 0.000028202351270 $pointGroupName; 
setKeyframe -at rotateY -t 28 -v 0.000010571612146 $pointGroupName; 
setKeyframe -at rotateZ -t 28 -v 0.000002342662827 $pointGroupName;
setKeyframe -at translateX -t 29 -v -0.000714760798651 $pointGroupName; 
setKeyframe -at translateY -t 29 -v 0.001469192597412 $pointGroupName; 
setKeyframe -at translateZ -t 29 -v -105.880385122993388 $pointGroupName; 
setKeyframe -at rotateX -t 29 -v 0.000033042147240 $pointGroupName; 
setKeyframe -at rotateY -t 29 -v 0.000011854765835 $pointGroupName; 
setKeyframe -at rotateZ -t 29 -v 0.000002619369527 $pointGroupName;
setKeyframe -at translateX -t 30 -v -0.000602832517792 $pointGroupName; 
setKeyframe -at translateY -t 30 -v 0.001296272333178 $pointGroupName; 
setKeyframe -at translateZ -t 30 -v -102.519260252784321 $pointGroupName; 
setKeyframe -at rotateX -t 30 -v 0.000029181137080 $pointGroupName; 
setKeyframe -at rotateY -t 30 -v 0.000009998285588 $pointGroupName; 
setKeyframe -at rotateZ -t 30 -v 0.000002202489276 $pointGroupName;
setKeyframe -at translateX -t 31 -v -0.000021945412374 $pointGroupName; 
setKeyframe -at translateY -t 31 -v 0.000049491288763 $pointGroupName; 
setKeyframe -at translateZ -t 31 -v -99.159596677286160 $pointGroupName; 
setKeyframe -at rotateX -t 31 -v 0.000001145166395 $pointGroupName; 
setKeyframe -at rotateY -t 31 -v 0.000000373785456 $pointGroupName; 
setKeyframe -at rotateZ -t 31 -v 0.000000082080690 $pointGroupName;
setKeyframe -at translateX -t 32 -v 0.000512977181241 $pointGroupName; 
setKeyframe -at translateY -t 32 -v -0.001216658923752 $pointGroupName; 
setKeyframe -at translateZ -t 32 -v -95.799981740337316 $pointGroupName; 
setKeyframe -at rotateX -t 32 -v -0.000027378901822 $pointGroupName; 
setKeyframe -at rotateY -t 32 -v -0.000008490619422 $pointGroupName; 
setKeyframe -at rotateZ -t 32 -v -0.000001858287941 $pointGroupName;
setKeyframe -at translateX -t 33 -v 0.000573071157707 $pointGroupName; 
setKeyframe -at translateY -t 33 -v -0.001433748917009 $pointGroupName; 
setKeyframe -at translateZ -t 33 -v -92.438946183851741 $pointGroupName; 
setKeyframe -at rotateX -t 33 -v -0.000032251641248 $pointGroupName; 
setKeyframe -at rotateY -t 33 -v -0.000009475014805 $pointGroupName; 
setKeyframe -at rotateZ -t 33 -v -0.000002066380182 $pointGroupName;
setKeyframe -at translateX -t 34 -v 0.000485540961495 $pointGroupName; 
setKeyframe -at translateY -t 34 -v -0.001285691434930 $pointGroupName; 
setKeyframe -at translateZ -t 34 -v -89.077408926766481 $pointGroupName; 
setKeyframe -at rotateX -t 34 -v -0.000028874968732 $pointGroupName; 
setKeyframe -at rotateY -t 34 -v -0.000008010259248 $pointGroupName; 
setKeyframe -at rotateZ -t 34 -v -0.000001740318051 $pointGroupName;
setKeyframe -at translateX -t 35 -v 0.000375831145611 $pointGroupName; 
setKeyframe -at translateY -t 35 -v -0.001057241452855 $pointGroupName; 
setKeyframe -at translateZ -t 35 -v -85.715757089571753 $pointGroupName; 
setKeyframe -at rotateX -t 35 -v -0.000023678186554 $pointGroupName; 
setKeyframe -at rotateY -t 35 -v -0.000006180053989 $pointGroupName; 
setKeyframe -at rotateZ -t 35 -v -0.000001337261527 $pointGroupName;
setKeyframe -at translateX -t 36 -v 0.000275068832657 $pointGroupName; 
setKeyframe -at translateY -t 36 -v -0.000825511905376 $pointGroupName; 
setKeyframe -at translateZ -t 36 -v -82.354096737942342 $pointGroupName; 
setKeyframe -at rotateX -t 36 -v -0.000018445986866 $pointGroupName; 
setKeyframe -at rotateY -t 36 -v -0.000004511088931 $pointGroupName; 
setKeyframe -at rotateZ -t 36 -v -0.000000971928727 $pointGroupName;
setKeyframe -at translateX -t 37 -v 0.000188331441954 $pointGroupName; 
setKeyframe -at translateY -t 37 -v -0.000605877614916 $pointGroupName; 
setKeyframe -at translateZ -t 37 -v -78.992449556784308 $pointGroupName; 
setKeyframe -at rotateX -t 37 -v -0.000013509506496 $pointGroupName; 
setKeyframe -at rotateY -t 37 -v -0.000003081219095 $pointGroupName; 
setKeyframe -at rotateZ -t 37 -v -0.000000660828640 $pointGroupName;
setKeyframe -at translateX -t 38 -v 0.000115840643645 $pointGroupName; 
setKeyframe -at translateY -t 38 -v -0.000401688509257 $pointGroupName; 
setKeyframe -at translateZ -t 38 -v -75.630820687780798 $pointGroupName; 
setKeyframe -at rotateX -t 38 -v -0.000008909706019 $pointGroupName; 
setKeyframe -at rotateY -t 38 -v -0.000001885001784 $pointGroupName; 
setKeyframe -at rotateZ -t 38 -v -0.000000402321807 $pointGroupName;
setKeyframe -at translateX -t 39 -v 0.000056253217686 $pointGroupName; 
setKeyframe -at translateY -t 39 -v -0.000211597738385 $pointGroupName; 
setKeyframe -at translateZ -t 39 -v -72.269208681222153 $pointGroupName; 
setKeyframe -at rotateX -t 39 -v -0.000004736452901 $pointGroupName; 
setKeyframe -at rotateY -t 39 -v -0.000000923732519 $pointGroupName; 
setKeyframe -at rotateZ -t 39 -v -0.000000196148353 $pointGroupName;
setKeyframe -at translateX -t 40 -v 0.000006860368210 $pointGroupName; 
setKeyframe -at translateY -t 40 -v -0.000028203360671 $pointGroupName; 
setKeyframe -at translateZ -t 40 -v -68.907603369095554 $pointGroupName; 
setKeyframe -at rotateX -t 40 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 40 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 40 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 41 -v -0.000027743025958 $pointGroupName; 
setKeyframe -at translateY -t 41 -v 0.000125771206285 $pointGroupName; 
setKeyframe -at translateZ -t 41 -v -65.546037666046175 $pointGroupName; 
setKeyframe -at rotateX -t 41 -v 0.000002663684800 $pointGroupName; 
setKeyframe -at rotateY -t 41 -v 0.000000431137881 $pointGroupName; 
setKeyframe -at rotateZ -t 41 -v 0.000000090541726 $pointGroupName;
setKeyframe -at translateX -t 42 -v -0.000041735777467 $pointGroupName; 
setKeyframe -at translateY -t 42 -v 0.000210926185304 $pointGroupName; 
setKeyframe -at translateZ -t 42 -v -62.184569214812740 $pointGroupName; 
setKeyframe -at rotateX -t 42 -v 0.000004468830175 $pointGroupName; 
setKeyframe -at rotateY -t 42 -v 0.000000649017476 $pointGroupName; 
setKeyframe -at rotateZ -t 42 -v 0.000000135489765 $pointGroupName;
setKeyframe -at translateX -t 43 -v -0.000049922845292 $pointGroupName; 
setKeyframe -at translateY -t 43 -v 0.000285089751841 $pointGroupName; 
setKeyframe -at translateZ -t 43 -v -58.823115569303255 $pointGroupName; 
setKeyframe -at rotateX -t 43 -v 0.000006104242244 $pointGroupName; 
setKeyframe -at rotateY -t 43 -v 0.000000784883058 $pointGroupName; 
setKeyframe -at rotateZ -t 43 -v 0.000000162837475 $pointGroupName;
setKeyframe -at translateX -t 44 -v -0.000052005673954 $pointGroupName; 
setKeyframe -at translateY -t 44 -v 0.000341417565153 $pointGroupName; 
setKeyframe -at translateZ -t 44 -v -55.461686977592777 $pointGroupName; 
setKeyframe -at rotateX -t 44 -v 0.000007296965449 $pointGroupName; 
setKeyframe -at rotateY -t 44 -v 0.000000816544663 $pointGroupName; 
setKeyframe -at rotateZ -t 44 -v 0.000000168310859 $pointGroupName;
setKeyframe -at translateX -t 45 -v -0.000048705676571 $pointGroupName; 
setKeyframe -at translateY -t 45 -v 0.000376083001271 $pointGroupName; 
setKeyframe -at translateZ -t 45 -v -52.100289433192785 $pointGroupName; 
setKeyframe -at rotateX -t 45 -v 0.000007971558612 $pointGroupName; 
setKeyframe -at rotateY -t 45 -v 0.000000758882857 $pointGroupName; 
setKeyframe -at rotateZ -t 45 -v 0.000000155372909 $pointGroupName;
setKeyframe -at translateX -t 46 -v -0.000041503534202 $pointGroupName; 
setKeyframe -at translateY -t 46 -v 0.000389061167738 $pointGroupName; 
setKeyframe -at translateZ -t 46 -v -48.738923414809605 $pointGroupName; 
setKeyframe -at rotateX -t 46 -v 0.000008162979417 $pointGroupName; 
setKeyframe -at rotateY -t 46 -v 0.000000640558497 $pointGroupName; 
setKeyframe -at rotateZ -t 46 -v 0.000000130231496 $pointGroupName;
setKeyframe -at translateX -t 47 -v -0.000032039233318 $pointGroupName; 
setKeyframe -at translateY -t 47 -v 0.000382165506039 $pointGroupName; 
setKeyframe -at translateZ -t 47 -v -45.377586663992361 $pointGroupName; 
setKeyframe -at rotateX -t 47 -v 0.000007901922930 $pointGroupName; 
setKeyframe -at rotateY -t 47 -v 0.000000487704565 $pointGroupName; 
setKeyframe -at rotateZ -t 47 -v 0.000000098437888 $pointGroupName;
setKeyframe -at translateX -t 48 -v -0.000021831287954 $pointGroupName; 
setKeyframe -at translateY -t 48 -v 0.000357915903621 $pointGroupName; 
setKeyframe -at translateZ -t 48 -v -42.016275805029920 $pointGroupName; 
setKeyframe -at rotateX -t 48 -v 0.000007336734864 $pointGroupName; 
setKeyframe -at rotateY -t 48 -v 0.000000329751643 $pointGroupName; 
setKeyframe -at rotateZ -t 48 -v 0.000000066059579 $pointGroupName;
setKeyframe -at translateX -t 49 -v -0.000012181865348 $pointGroupName; 
setKeyframe -at translateY -t 49 -v 0.000319208244576 $pointGroupName; 
setKeyframe -at translateZ -t 49 -v -38.654986825744501 $pointGroupName; 
setKeyframe -at rotateX -t 49 -v 0.000006499470247 $pointGroupName; 
setKeyframe -at rotateY -t 49 -v 0.000000182951573 $pointGroupName; 
setKeyframe -at rotateZ -t 49 -v 0.000000036368678 $pointGroupName;
setKeyframe -at translateX -t 50 -v -0.000004131693624 $pointGroupName; 
setKeyframe -at translateY -t 50 -v 0.000269247678858 $pointGroupName; 
setKeyframe -at translateZ -t 50 -v -35.293715167122684 $pointGroupName; 
setKeyframe -at rotateX -t 50 -v 0.000005399378573 $pointGroupName; 
setKeyframe -at rotateY -t 50 -v 0.000000061180039 $pointGroupName; 
setKeyframe -at rotateZ -t 50 -v 0.000000012065580 $pointGroupName;
setKeyframe -at translateX -t 51 -v 0.000001578326298 $pointGroupName; 
setKeyframe -at translateY -t 51 -v 0.000211882438236 $pointGroupName; 
setKeyframe -at translateZ -t 51 -v -31.932455220161330 $pointGroupName; 
setKeyframe -at rotateX -t 51 -v 0.000004182553734 $pointGroupName; 
setKeyframe -at rotateY -t 51 -v -0.000000023032572 $pointGroupName; 
setKeyframe -at rotateZ -t 51 -v -0.000000004505406 $pointGroupName;
setKeyframe -at translateX -t 52 -v 0.000004624068861 $pointGroupName; 
setKeyframe -at translateY -t 52 -v 0.000153049196257 $pointGroupName; 
setKeyframe -at translateZ -t 52 -v -28.571198138309668 $pointGroupName; 
setKeyframe -at rotateX -t 52 -v 0.000002956791573 $pointGroupName; 
setKeyframe -at rotateY -t 52 -v -0.000000066123610 $pointGroupName; 
setKeyframe -at rotateZ -t 52 -v -0.000000012826794 $pointGroupName;
setKeyframe -at translateX -t 53 -v 0.000005447935660 $pointGroupName; 
setKeyframe -at translateY -t 53 -v 0.000102909592783 $pointGroupName; 
setKeyframe -at translateZ -t 53 -v -25.209928563834524 $pointGroupName; 
setKeyframe -at rotateX -t 53 -v 0.000001706185879 $pointGroupName; 
setKeyframe -at rotateY -t 53 -v -0.000000066945641 $pointGroupName; 
setKeyframe -at rotateZ -t 53 -v -0.000000012875712 $pointGroupName;
setKeyframe -at translateX -t 54 -v 0.000004773227548 $pointGroupName; 
setKeyframe -at translateY -t 54 -v 0.000063121062468 $pointGroupName; 
setKeyframe -at translateZ -t 54 -v -21.848643822876738 $pointGroupName; 
setKeyframe -at rotateX -t 54 -v 0.000001205452169 $pointGroupName; 
setKeyframe -at rotateY -t 54 -v -0.000000067657556 $pointGroupName; 
setKeyframe -at rotateZ -t 54 -v -0.000000012899694 $pointGroupName;
setKeyframe -at translateX -t 55 -v -0.000003131851637 $pointGroupName; 
setKeyframe -at translateY -t 55 -v -0.000031876521362 $pointGroupName; 
setKeyframe -at translateZ -t 55 -v -18.487443426342352 $pointGroupName; 
setKeyframe -at rotateX -t 55 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 55 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 55 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 56 -v -0.000011827959696 $pointGroupName; 
setKeyframe -at translateY -t 56 -v -0.000097897283993 $pointGroupName; 
setKeyframe -at translateZ -t 56 -v -15.126199726065295 $pointGroupName; 
setKeyframe -at rotateX -t 56 -v -0.000001700442688 $pointGroupName; 
setKeyframe -at rotateY -t 56 -v 0.000000152944449 $pointGroupName; 
setKeyframe -at rotateZ -t 56 -v 0.000000028642903 $pointGroupName;
setKeyframe -at translateX -t 57 -v -0.000020838481390 $pointGroupName; 
setKeyframe -at translateY -t 57 -v -0.000145392718238 $pointGroupName; 
setKeyframe -at translateZ -t 57 -v -11.764928273324173 $pointGroupName; 
setKeyframe -at rotateX -t 57 -v -0.000002684061093 $pointGroupName; 
setKeyframe -at rotateY -t 57 -v 0.000000286839937 $pointGroupName; 
setKeyframe -at rotateZ -t 57 -v 0.000000053228631 $pointGroupName;
setKeyframe -at translateX -t 58 -v -0.000029916269291 $pointGroupName; 
setKeyframe -at translateY -t 58 -v -0.000180480267034 $pointGroupName; 
setKeyframe -at translateZ -t 58 -v -8.403638181243920 $pointGroupName; 
setKeyframe -at rotateX -t 58 -v -0.000003169517916 $pointGroupName; 
setKeyframe -at rotateY -t 58 -v 0.000000392382360 $pointGroupName; 
setKeyframe -at rotateZ -t 58 -v 0.000000072141578 $pointGroupName;
setKeyframe -at translateX -t 59 -v -0.000038526399063 $pointGroupName; 
setKeyframe -at translateY -t 59 -v -0.000204802238287 $pointGroupName; 
setKeyframe -at translateZ -t 59 -v -5.042331796784950 $pointGroupName; 
setKeyframe -at rotateX -t 59 -v -0.000003585752854 $pointGroupName; 
setKeyframe -at rotateY -t 59 -v 0.000000504636740 $pointGroupName; 
setKeyframe -at rotateZ -t 59 -v 0.000000091913677 $pointGroupName;
setKeyframe -at translateX -t 60 -v -0.000045976644302 $pointGroupName; 
setKeyframe -at translateY -t 60 -v -0.000218533491719 $pointGroupName; 
setKeyframe -at translateZ -t 60 -v -1.681009245550996 $pointGroupName; 
setKeyframe -at rotateX -t 60 -v -0.000003770110653 $pointGroupName; 
setKeyframe -at rotateY -t 60 -v 0.000000594434363 $pointGroupName; 
setKeyframe -at rotateZ -t 60 -v 0.000000107248432 $pointGroupName;
setKeyframe -at translateX -t 61 -v -0.000051609827693 $pointGroupName; 
setKeyframe -at translateY -t 61 -v -0.000221911357812 $pointGroupName; 
setKeyframe -at translateZ -t 61 -v 1.680329238041594 $pointGroupName; 
setKeyframe -at rotateX -t 61 -v -0.000003759511652 $pointGroupName; 
setKeyframe -at rotateY -t 61 -v 0.000000656429538 $pointGroupName; 
setKeyframe -at rotateZ -t 61 -v 0.000000117308022 $pointGroupName;
setKeyframe -at translateX -t 62 -v -0.000054890349546 $pointGroupName; 
setKeyframe -at translateY -t 62 -v -0.000215546474124 $pointGroupName; 
setKeyframe -at translateZ -t 62 -v 5.041682827449961 $pointGroupName; 
setKeyframe -at rotateX -t 62 -v -0.000003747948494 $pointGroupName; 
setKeyframe -at rotateY -t 62 -v 0.000000717862662 $pointGroupName; 
setKeyframe -at rotateZ -t 62 -v 0.000000127059274 $pointGroupName;
setKeyframe -at translateX -t 63 -v -0.000055433490612 $pointGroupName; 
setKeyframe -at translateY -t 63 -v -0.000200379067536 $pointGroupName; 
setKeyframe -at translateZ -t 63 -v 8.403050165931404 $pointGroupName; 
setKeyframe -at rotateX -t 63 -v -0.000003341091535 $pointGroupName; 
setKeyframe -at rotateY -t 63 -v 0.000000696471757 $pointGroupName; 
setKeyframe -at rotateZ -t 63 -v 0.000000122087936 $pointGroupName;
setKeyframe -at translateX -t 64 -v -0.000052943155705 $pointGroupName; 
setKeyframe -at translateY -t 64 -v -0.000177349931874 $pointGroupName; 
setKeyframe -at translateZ -t 64 -v 11.764429873227982 $pointGroupName; 
setKeyframe -at rotateX -t 64 -v -0.000002883097546 $pointGroupName; 
setKeyframe -at rotateY -t 64 -v 0.000000649752377 $pointGroupName; 
setKeyframe -at rotateZ -t 64 -v 0.000000112799164 $pointGroupName;
setKeyframe -at translateX -t 65 -v -0.000046805655451 $pointGroupName; 
setKeyframe -at translateY -t 65 -v -0.000146133690919 $pointGroupName; 
setKeyframe -at translateZ -t 65 -v 15.125822526646033 $pointGroupName; 
setKeyframe -at rotateX -t 65 -v -0.000002345026722 $pointGroupName; 
setKeyframe -at rotateY -t 65 -v 0.000000568106938 $pointGroupName; 
setKeyframe -at rotateZ -t 65 -v 0.000000097671329 $pointGroupName;
setKeyframe -at translateX -t 66 -v -0.000035107850000 $pointGroupName; 
setKeyframe -at translateY -t 66 -v -0.000102670307882 $pointGroupName; 
setKeyframe -at translateZ -t 66 -v 18.487234532985752 $pointGroupName; 
setKeyframe -at rotateX -t 66 -v -0.000001651444701 $pointGroupName; 
setKeyframe -at rotateY -t 66 -v 0.000000427947724 $pointGroupName; 
setKeyframe -at rotateZ -t 66 -v 0.000000072862205 $pointGroupName;
setKeyframe -at translateX -t 67 -v -0.000014236956492 $pointGroupName; 
setKeyframe -at translateY -t 67 -v -0.000039168333046 $pointGroupName; 
setKeyframe -at translateZ -t 67 -v 21.848678181166918 $pointGroupName; 
setKeyframe -at rotateX -t 67 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 67 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 67 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 68 -v -0.000009766633191 $pointGroupName; 
setKeyframe -at translateY -t 68 -v -0.000025375090800 $pointGroupName; 
setKeyframe -at translateZ -t 68 -v 25.210044241658750 $pointGroupName; 
setKeyframe -at rotateX -t 68 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 68 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 68 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 69 -v -0.000001451925698 $pointGroupName; 
setKeyframe -at translateY -t 69 -v -0.000003574664618 $pointGroupName; 
setKeyframe -at translateZ -t 69 -v 28.571422956026851 $pointGroupName; 
setKeyframe -at rotateX -t 69 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 69 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 69 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 70 -v 0.000010799694266 $pointGroupName; 
setKeyframe -at translateY -t 70 -v 0.000025273141645 $pointGroupName; 
setKeyframe -at translateZ -t 70 -v 31.932812869509178 $pointGroupName; 
setKeyframe -at rotateX -t 70 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 70 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 70 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 71 -v 0.000024004570236 $pointGroupName; 
setKeyframe -at translateY -t 71 -v 0.000053542124618 $pointGroupName; 
setKeyframe -at translateZ -t 71 -v 35.294202005610714 $pointGroupName; 
setKeyframe -at rotateX -t 71 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 71 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 71 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 72 -v 0.000036490925403 $pointGroupName; 
setKeyframe -at translateY -t 72 -v 0.000077772283618 $pointGroupName; 
setKeyframe -at translateZ -t 72 -v 38.655584889754522 $pointGroupName; 
setKeyframe -at rotateX -t 72 -v 0.000001134453942 $pointGroupName; 
setKeyframe -at rotateY -t 72 -v -0.000000408133203 $pointGroupName; 
setKeyframe -at rotateZ -t 72 -v -0.000000065577596 $pointGroupName;
setKeyframe -at translateX -t 73 -v 0.000047374703243 $pointGroupName; 
setKeyframe -at translateY -t 73 -v 0.000096696758490 $pointGroupName; 
setKeyframe -at translateZ -t 73 -v 42.016959484405078 $pointGroupName; 
setKeyframe -at rotateX -t 73 -v 0.000001128251286 $pointGroupName; 
setKeyframe -at rotateY -t 73 -v -0.000000424664024 $pointGroupName; 
setKeyframe -at rotateZ -t 73 -v -0.000000067589798 $pointGroupName;
setKeyframe -at translateX -t 74 -v 0.000056070085535 $pointGroupName; 
setKeyframe -at translateY -t 74 -v 0.000109830917026 $pointGroupName; 
setKeyframe -at translateZ -t 74 -v 45.378324982011719 $pointGroupName; 
setKeyframe -at rotateX -t 74 -v 0.000001586605442 $pointGroupName; 
setKeyframe -at rotateY -t 74 -v -0.000000623487721 $pointGroupName; 
setKeyframe -at rotateZ -t 74 -v -0.000000098305588 $pointGroupName;
setKeyframe -at translateX -t 75 -v 0.000062147491974 $pointGroupName; 
setKeyframe -at translateY -t 75 -v 0.000117050554934 $pointGroupName; 
setKeyframe -at translateZ -t 75 -v 48.739681149628439 $pointGroupName; 
setKeyframe -at rotateX -t 75 -v 0.000001577431372 $pointGroupName; 
setKeyframe -at rotateY -t 75 -v -0.000000645946533 $pointGroupName; 
setKeyframe -at rotateZ -t 75 -v -0.000000100901445 $pointGroupName;
setKeyframe -at translateX -t 76 -v 0.000065339681157 $pointGroupName; 
setKeyframe -at translateY -t 76 -v 0.000118535020576 $pointGroupName; 
setKeyframe -at translateZ -t 76 -v 52.101028236237624 $pointGroupName; 
setKeyframe -at rotateX -t 76 -v 0.000001568085490 $pointGroupName; 
setKeyframe -at rotateY -t 76 -v -0.000000667936186 $pointGroupName; 
setKeyframe -at rotateZ -t 76 -v -0.000000103377488 $pointGroupName;
setKeyframe -at translateX -t 77 -v 0.000065653447045 $pointGroupName; 
setKeyframe -at translateY -t 77 -v 0.000114908622862 $pointGroupName; 
setKeyframe -at translateZ -t 77 -v 55.462367203471558 $pointGroupName; 
setKeyframe -at rotateX -t 77 -v 0.000001558586875 $pointGroupName; 
setKeyframe -at rotateY -t 77 -v -0.000000689452210 $pointGroupName; 
setKeyframe -at rotateZ -t 77 -v -0.000000105737231 $pointGroupName;
setKeyframe -at translateX -t 78 -v 0.000063873309792 $pointGroupName; 
setKeyframe -at translateY -t 78 -v 0.000108017523843 $pointGroupName; 
setKeyframe -at translateZ -t 78 -v 58.823700961243361 $pointGroupName; 
setKeyframe -at rotateX -t 78 -v 0.000001095275949 $pointGroupName; 
setKeyframe -at rotateY -t 78 -v -0.000000502393446 $pointGroupName; 
setKeyframe -at rotateZ -t 78 -v -0.000000076356391 $pointGroupName;
setKeyframe -at translateX -t 79 -v 0.000062683367247 $pointGroupName; 
setKeyframe -at translateY -t 79 -v 0.000102568791320 $pointGroupName; 
setKeyframe -at translateZ -t 79 -v 62.185036980080355 $pointGroupName; 
setKeyframe -at rotateX -t 79 -v 0.000001088382505 $pointGroupName; 
setKeyframe -at rotateY -t 79 -v -0.000000516932221 $pointGroupName; 
setKeyframe -at rotateZ -t 79 -v -0.000000077868345 $pointGroupName;
setKeyframe -at translateX -t 80 -v 0.000066994745929 $pointGroupName; 
setKeyframe -at translateY -t 80 -v 0.000106208437685 $pointGroupName; 
setKeyframe -at translateZ -t 80 -v 65.546387429090316 $pointGroupName; 
setKeyframe -at rotateX -t 80 -v 0.000001081419358 $pointGroupName; 
setKeyframe -at rotateY -t 80 -v -0.000000531132364 $pointGroupName; 
setKeyframe -at rotateZ -t 80 -v -0.000000079306131 $pointGroupName;
setKeyframe -at translateX -t 81 -v 0.000050066239318 $pointGroupName; 
setKeyframe -at translateY -t 81 -v 0.000076992553133 $pointGroupName; 
setKeyframe -at translateZ -t 81 -v 68.907685577781507 $pointGroupName; 
setKeyframe -at rotateX -t 81 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 81 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 81 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 82 -v 0.000027733322717 $pointGroupName; 
setKeyframe -at translateY -t 82 -v 0.000041417861894 $pointGroupName; 
setKeyframe -at translateZ -t 82 -v 72.268973530168267 $pointGroupName; 
setKeyframe -at rotateX -t 82 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 82 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 82 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 83 -v 0.000011712368156 $pointGroupName; 
setKeyframe -at translateY -t 83 -v 0.000017005075932 $pointGroupName; 
setKeyframe -at translateZ -t 83 -v 75.630279200132577 $pointGroupName; 
setKeyframe -at rotateX -t 83 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 83 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 83 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 84 -v -0.000001644070302 $pointGroupName; 
setKeyframe -at translateY -t 84 -v -0.000002322954131 $pointGroupName; 
setKeyframe -at translateZ -t 84 -v 78.991592935384602 $pointGroupName; 
setKeyframe -at rotateX -t 84 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 84 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 84 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 85 -v -0.000013806645995 $pointGroupName; 
setKeyframe -at translateY -t 85 -v -0.000019002372056 $pointGroupName; 
setKeyframe -at translateZ -t 85 -v 82.352910866828154 $pointGroupName; 
setKeyframe -at rotateX -t 85 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 85 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 85 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 86 -v -0.000024815151505 $pointGroupName; 
setKeyframe -at translateY -t 86 -v -0.000033298574706 $pointGroupName; 
setKeyframe -at translateZ -t 86 -v 85.714232583203625 $pointGroupName; 
setKeyframe -at rotateX -t 86 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 86 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 86 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 87 -v -0.000034304265121 $pointGroupName; 
setKeyframe -at translateY -t 87 -v -0.000044917368527 $pointGroupName; 
setKeyframe -at translateZ -t 87 -v 89.075558561163973 $pointGroupName; 
setKeyframe -at rotateX -t 87 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 87 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 87 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 88 -v -0.000041922112544 $pointGroupName; 
setKeyframe -at translateY -t 88 -v -0.000053606263833 $pointGroupName; 
setKeyframe -at translateZ -t 88 -v 92.436889210729703 $pointGroupName; 
setKeyframe -at rotateX -t 88 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 88 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 88 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 89 -v -0.000047418763089 $pointGroupName; 
setKeyframe -at translateY -t 89 -v -0.000059259689323 $pointGroupName; 
setKeyframe -at translateZ -t 89 -v 95.798224706036763 $pointGroupName; 
setKeyframe -at rotateX -t 89 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 89 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 89 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 90 -v -0.000050604529065 $pointGroupName; 
setKeyframe -at translateY -t 90 -v -0.000061851335431 $pointGroupName; 
setKeyframe -at translateZ -t 90 -v 99.159565093088872 $pointGroupName; 
setKeyframe -at rotateX -t 90 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 90 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 90 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 91 -v -0.000051055662937 $pointGroupName; 
setKeyframe -at translateY -t 91 -v -0.000061073436129 $pointGroupName; 
setKeyframe -at translateZ -t 91 -v 102.520910864796832 $pointGroupName; 
setKeyframe -at rotateX -t 91 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 91 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 91 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 92 -v -0.000047369524623 $pointGroupName; 
setKeyframe -at translateY -t 92 -v -0.000055493219634 $pointGroupName; 
setKeyframe -at translateZ -t 92 -v 105.882264312344432 $pointGroupName; 
setKeyframe -at rotateX -t 92 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 92 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 92 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 93 -v -0.000036686168542 $pointGroupName; 
setKeyframe -at translateY -t 93 -v -0.000042115886771 $pointGroupName; 
setKeyframe -at translateZ -t 93 -v 109.243630216805798 $pointGroupName; 
setKeyframe -at rotateX -t 93 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 93 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 93 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 94 -v -0.000031881473149 $pointGroupName; 
setKeyframe -at translateY -t 94 -v -0.000035887427472 $pointGroupName; 
setKeyframe -at translateZ -t 94 -v 112.604984705995946 $pointGroupName; 
setKeyframe -at rotateX -t 94 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 94 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 94 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 95 -v -0.000036296150938 $pointGroupName; 
setKeyframe -at translateY -t 95 -v -0.000040083974469 $pointGroupName; 
setKeyframe -at translateZ -t 95 -v 115.966322549453736 $pointGroupName; 
setKeyframe -at rotateX -t 95 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 95 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 95 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 96 -v -0.000033737099145 $pointGroupName; 
setKeyframe -at translateY -t 96 -v -0.000036572874436 $pointGroupName; 
setKeyframe -at translateZ -t 96 -v 119.327672702016201 $pointGroupName; 
setKeyframe -at rotateX -t 96 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 96 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 96 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 97 -v -0.000028277779492 $pointGroupName; 
setKeyframe -at translateY -t 97 -v -0.000030106647102 $pointGroupName; 
setKeyframe -at translateZ -t 97 -v 122.689027573059406 $pointGroupName; 
setKeyframe -at rotateX -t 97 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 97 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 97 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 98 -v -0.000022280930338 $pointGroupName; 
setKeyframe -at translateY -t 98 -v -0.000023309396227 $pointGroupName; 
setKeyframe -at translateZ -t 98 -v 126.050382969794782 $pointGroupName; 
setKeyframe -at rotateX -t 98 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 98 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 98 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 99 -v -0.000016674764396 $pointGroupName; 
setKeyframe -at translateY -t 99 -v -0.000017149197191 $pointGroupName; 
setKeyframe -at translateZ -t 99 -v 129.411737346037569 $pointGroupName; 
setKeyframe -at rotateX -t 99 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 99 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 99 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 100 -v -0.000011807237470 $pointGroupName; 
setKeyframe -at translateY -t 100 -v -0.000011943069339 $pointGroupName; 
setKeyframe -at translateZ -t 100 -v 132.773090195857634 $pointGroupName; 
setKeyframe -at rotateX -t 100 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 100 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 100 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 101 -v -0.000007824543516 $pointGroupName; 
setKeyframe -at translateY -t 101 -v -0.000007787522804 $pointGroupName; 
setKeyframe -at translateZ -t 101 -v 136.134441365879638 $pointGroupName; 
setKeyframe -at rotateX -t 101 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 101 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 101 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 102 -v -0.000004748089964 $pointGroupName; 
setKeyframe -at translateY -t 102 -v -0.000004651717589 $pointGroupName; 
setKeyframe -at translateZ -t 102 -v 139.495790905291642 $pointGroupName; 
setKeyframe -at rotateX -t 102 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 102 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 102 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 103 -v -0.000002460840776 $pointGroupName; 
setKeyframe -at translateY -t 103 -v -0.000002374139612 $pointGroupName; 
setKeyframe -at translateZ -t 103 -v 142.857139074749284 $pointGroupName; 
setKeyframe -at rotateX -t 103 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 103 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 103 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 104 -v -0.000000615999468 $pointGroupName; 
setKeyframe -at translateY -t 104 -v -0.000000585462018 $pointGroupName; 
setKeyframe -at translateZ -t 104 -v 146.218486462708540 $pointGroupName; 
setKeyframe -at rotateX -t 104 -v -0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 104 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 104 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 105 -v 0.000001620673117 $pointGroupName; 
setKeyframe -at translateY -t 105 -v 0.000001517995315 $pointGroupName; 
setKeyframe -at translateZ -t 105 -v 149.579834349128333 $pointGroupName; 
setKeyframe -at rotateX -t 105 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 105 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 105 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 106 -v 0.000005797352571 $pointGroupName; 
setKeyframe -at translateY -t 106 -v 0.000005353231487 $pointGroupName; 
setKeyframe -at translateZ -t 106 -v 152.941184987293752 $pointGroupName; 
setKeyframe -at rotateX -t 106 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 106 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 106 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 107 -v 0.000009749195385 $pointGroupName; 
setKeyframe -at translateY -t 107 -v 0.000008878002859 $pointGroupName; 
setKeyframe -at translateZ -t 107 -v 156.302535124399924 $pointGroupName; 
setKeyframe -at rotateX -t 107 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 107 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 107 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 108 -v 0.000006434551295 $pointGroupName; 
setKeyframe -at translateY -t 108 -v 0.000005780538899 $pointGroupName; 
setKeyframe -at translateZ -t 108 -v 159.663874732302361 $pointGroupName; 
setKeyframe -at rotateX -t 108 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 108 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 108 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 109 -v 0.000009074545432 $pointGroupName; 
setKeyframe -at translateY -t 109 -v 0.000008044823517 $pointGroupName; 
setKeyframe -at translateZ -t 109 -v 163.025222861415216 $pointGroupName; 
setKeyframe -at rotateX -t 109 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 109 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 109 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 110 -v 0.000015766497825 $pointGroupName; 
setKeyframe -at translateY -t 110 -v 0.000013797534706 $pointGroupName; 
setKeyframe -at translateZ -t 110 -v 166.386576523457848 $pointGroupName; 
setKeyframe -at rotateX -t 110 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 110 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 110 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 111 -v 0.000025606345105 $pointGroupName; 
setKeyframe -at translateY -t 111 -v 0.000022126702376 $pointGroupName; 
setKeyframe -at translateZ -t 111 -v 169.747934261433301 $pointGroupName; 
setKeyframe -at rotateX -t 111 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 111 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 111 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 112 -v 0.000038523511066 $pointGroupName; 
setKeyframe -at translateY -t 112 -v 0.000032879215667 $pointGroupName; 
setKeyframe -at translateZ -t 112 -v 173.109295823484501 $pointGroupName; 
setKeyframe -at rotateX -t 112 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 112 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 112 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 113 -v 0.000054680166897 $pointGroupName; 
setKeyframe -at translateY -t 113 -v 0.000046107458346 $pointGroupName; 
setKeyframe -at translateZ -t 113 -v 176.470661286611346 $pointGroupName; 
setKeyframe -at rotateX -t 113 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 113 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 113 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 114 -v 0.000074182866214 $pointGroupName; 
setKeyframe -at translateY -t 114 -v 0.000061816701077 $pointGroupName; 
setKeyframe -at translateZ -t 114 -v 179.832030649735145 $pointGroupName; 
setKeyframe -at rotateX -t 114 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 114 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 114 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 115 -v 0.000097002735941 $pointGroupName; 
setKeyframe -at translateY -t 115 -v 0.000079902095322 $pointGroupName; 
setKeyframe -at translateZ -t 115 -v 183.193403738292716 $pointGroupName; 
setKeyframe -at rotateX -t 115 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 115 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 115 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 116 -v 0.000122837832819 $pointGroupName; 
setKeyframe -at translateY -t 116 -v 0.000100042740939 $pointGroupName; 
setKeyframe -at translateZ -t 116 -v 186.554780036381914 $pointGroupName; 
setKeyframe -at rotateX -t 116 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 116 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 116 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 117 -v 0.000149990647287 $pointGroupName; 
setKeyframe -at translateY -t 117 -v 0.000120809333154 $pointGroupName; 
setKeyframe -at translateZ -t 117 -v 189.916157278004789 $pointGroupName; 
setKeyframe -at rotateX -t 117 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 117 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 117 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 118 -v 0.000169391318110 $pointGroupName; 
setKeyframe -at translateY -t 118 -v 0.000134961668579 $pointGroupName; 
setKeyframe -at translateZ -t 118 -v 193.277524027131022 $pointGroupName; 
setKeyframe -at rotateX -t 118 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 118 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 118 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 119 -v 0.000147025511708 $pointGroupName; 
setKeyframe -at translateY -t 119 -v 0.000115902211220 $pointGroupName; 
setKeyframe -at translateZ -t 119 -v 196.638838340131002 $pointGroupName; 
setKeyframe -at rotateX -t 119 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 119 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 119 -v 0.000000000000000 $pointGroupName;
setKeyframe -at translateX -t 120 -v -0.000000000001577 $pointGroupName; 
setKeyframe -at translateY -t 120 -v -0.000000000001151 $pointGroupName; 
setKeyframe -at translateZ -t 120 -v 199.999999999997783 $pointGroupName; 
setKeyframe -at rotateX -t 120 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateY -t 120 -v 0.000000000000000 $pointGroupName; 
setKeyframe -at rotateZ -t 120 -v 0.000000000000000 $pointGroupName;
xform -zeroTransformPivots -rotateOrder zxy -translation 0.000000000000000 0.000000000000000 0.000000000000000 -scale 1.000000000000000 1.000000000000000 1.000000000000000 -rotation -0.000000000000000 0.000000000000000 0.000000000000000 $sceneGroupName;


